import re

# Let's define a rich dictionary for full sentence & phrase translation
DEEP_PHRASES_ES = [
    # Clean headers
    (r'^[A-Za-z0-9\s\'\-]+\n(?=[A-Z0-9\+💡])', ''),
    (r'\bAttacks that Critically Strike gain an additional\b', 'Los ataques críticos otorgan un'),
    (r'\bAttacks that Critically Strike gain an additional 4% Vampirismo Físico\b', 'Los ataques que asestan golpes críticos otorgan un 4% adicional de Vampirismo Físico'),
    (r'\bauto-attack carries\b', 'tiradores e hiper-carries de autoataques'),
    (r'\bauto-attack fighters\b', 'luchadores de autoataques'),
    (r'\bauto-attackers\b', 'tiradores y campeones de autoataque'),
    (r'\bauto-attacks\b', 'autoataques'),
    (r'\bauto-attack\b', 'autoataque'),
    (r'\bauto attacks\b', 'autoataques'),
    (r'\bauto attack\b', 'autoataque'),
    (r'\bbasic attacks\b', 'ataques básicos'),
    (r'\bbasic attack\b', 'ataque básico'),
    (r'\bwho need a second chance in teamfights\b', 'que necesitan una segunda oportunidad en peleas de equipo'),
    (r'\bwith high burst damage, such as\b', 'con alto daño explosivo como'),
    (r'\bas well as against strong diving champions like\b', 'así como contra iniciadores agresivos como'),
    (r'\bas well as against strong diving Campeones like\b', 'así como contra iniciadores agresivos como'),
    (r'\bThis item extends your attack range and adds hybrid damage by empowering every fourth attack with a magic burst that can bounce to multiple targets and critically strike\b', 'Este objeto aumenta tu alcance de ataque y añade daño híbrido potenciando ataques con ráfagas mágicas que rebotan entre múltiples objetivos y pueden asestar golpes críticos'),
    (r'\bMoving and attacking charges the empowered strike, and upon activation you gain a hefty movement speed boost, aiding both chase and retreat\b', 'Moverse y atacar carga el golpe potenciado, otorgando un gran aumento de velocidad de movimiento al activarse para perseguir o escapar'),
    (r'\bPerfect for marksmen and auto‑attack bruisers who want more reach, multi‑target damage, and extra mobility in skirmishes\b', 'Perfecto para tiradores y colosos de autoataques que buscan mayor alcance, daño en área y movilidad en escaramuzas'),
    (r'\bPerfect for marksmen and auto-attack bruisers who want more reach, multi-target damage, and extra mobility in skirmishes\b', 'Perfecto para tiradores y colosos de autoataques que buscan mayor alcance, daño en área y movilidad en escaramuzas'),
    (r'\bThis item turns your basic attacks into multi-target pressure: each attack fires extra bolts at nearby enemies that can trigger on-hit effects and crits\b', 'Este objeto convierte tus ataques básicos en daño multi-objetivo: cada impacto dispara proyectiles adicionales a enemigos cercanos que activan efectos de impacto y golpes críticos'),
    (r'\bIt greatly improves waveclear, contributes strong multi-target damage in teamfights, and makes trading on single targets much riskier for the opponent due to distributed damage\b', 'Mejora enormemente la limpieza de oleadas y aporta daño masivo en peleas de equipo'),
    (r'\bPerfect for marksmen and on-hit builds who value sustained attack cadence and AOE presence\b', 'Perfecto para tiradores y composiciones de efectos de impacto que buscan cadencia de ataque sostenida y presencia en área'),
    (r'\bMelee users can use it too, but it shines brightest on ranged auto-attackers\b', 'Brilla especialmente en tiradores y campeones a distancia'),
    (r'\bThis item provides massive flat armor penetration, high attack damage, and a powerful movement speed boost when out of combat and on-demand\b', 'Otorga una enorme penetración de armadura fija, alto daño de ataque y gran velocidad de movimiento fuera de combate'),
    (r'\bIt enables rapid roaming, aggressive flanks, and decisive gap-closing for assassins\b', 'Permite rotaciones rápidas, flanqueos agresivos y cierres de brecha letales para asesinos'),
    (r'\bBest for AD assassins and roamers\b', 'Excelente para asesinos AD y campeones con alta rotación en el mapa'),
    (r'\bThis item grants high attack damage and armor penetration, and its Nightstalker passive makes your first attack from unseen positions deal heavy bonus damage and slow the target\b', 'Otorga gran daño de ataque y penetración de armadura; su pasiva Acechador Nocturno inflige gran daño adicional y ralentiza con el primer ataque al salir del sigilo'),
    (r'\bIdeal for burst assassins who want instant one-shot potential and sticking power on priority carries\b', 'Ideal para asesinos de daño explosivo que buscan eliminar objetivos prioritarios instantáneamente'),
    (r'\bThis item is the cornerstone of critical strike builds, drastically boosting critical strike damage\b', 'Es el pilar fundamental de las builds de impacto crítico, aumentando drásticamente el daño de los golpes críticos'),
    (r'\bEssential for marksmen and crit-scaling champions in the mid-to-late game to maximize burst and sustained DPS\b', 'Esencial para tiradores y campeones de escalado crítico en juego medio y tardío para maximizar el DPS sostenido'),
    (r'\bThis item is essential for champions looking to maximize their critical strike damage\b', 'Este objeto es esencial para maximizar el daño de impacto crítico'),
    (r'\bThis item is perfect for auto‑attackers who need to shred through armor and cut down enemy healing\b', 'Este objeto es perfecto para destruir armaduras y neutralizar la curación enemiga'),
    (r'\bThis item is perfect for auto-attackers who need to shred through armor and cut down enemy healing\b', 'Este objeto es perfecto para destruir armaduras y neutralizar la curación enemiga'),
    (r'\bIt boosts your penetration to deal more damage against tanky targets and applies grievous wounds on hit, reducing all healing and regen effects\b', 'Aumenta tu penetración contra tanques y aplica Heridas Graves al impacto, reduciendo la regeneración y curaciones enemigas'),
    (r'\bIdeal against tanks and high‑heal champions, and for marksmen and auto‑attack fighters who need to pierce defenses and curb enemy sustain\b', 'Ideal contra tanques y campeones con alta curación, permitiendo penetrar defensas y cortar el sustain rival'),
    (r'\bIdeal against tanks and high-heal champions, and for marksmen and auto-attack fighters who need to pierce defenses and curb enemy sustain\b', 'Ideal contra tanques y campeones con alta curación, permitiendo penetrar defensas y cortar el sustain rival'),
    (r'\bThis item is perfect for champions who deal physical damage and need to fight tanky opponents\b', 'Este objeto es ideal para campeones AD que enfrentan tanques y colosos con alta resistencia'),
    (r'\bThe "Sunder" effect reduces the enemy’s armor when dealing physical damage, making it effective at shredding through tanks with high resistance\b', 'La pasiva Hender reduce progresivamente la armadura del objetivo al infligir daño físico'),
    (r'\bThe movement speed bonus, activated when dealing physical damage, helps maintain mobility on the battlefield\b', 'La bonificación de velocidad de movimiento al infligir daño físico ayuda a mantener la movilidad en combate'),
    (r'\bIt\'s a great choice for fighters and junglers who can quickly apply multiple stacks of the item’s passive, reducing the enemy\'s armor and increasing the overall damage dealt\b', 'Excelente elección para luchadores y junglas que aplican acumulaciones rápidamente para reducir la armadura enemiga'),
    (r'\bThis item is perfect for AD champions who rely on mana and abilities to deal damage\b', 'Ideal para campeones AD que dependen del maná y uso constante de habilidades para infligir daño'),
    (r'\bIt provides bonuses to attack damage, maximum mana, and ability haste, allowing you to use your abilities effectively\b', 'Otorga daño de ataque, maná máximo y aceleración de habilidad para optimizar el uso de habilidades'),
    (r'\bThe "Mana Charge" effect increases your mana with each attack or mana usage, which significantly boosts your damage once the item is completed\b', 'La pasiva Carga de Maná incrementa tu reserva con cada impacto o habilidad usada'),
    (r'\bAfter reaching the maximum bonus mana, the item transforms into Muramana, greatly enhancing your attacks\b', 'Al llegar al máximo de maná acumulado, se transforma en Muramana, potenciando enormemente los ataques'),
    (r'\bIt’s an excellent choice for champions who use mana to activate their abilities, such as Ezreal or Twitch\b', 'Excelente para campeones lanzadores de habilidades como Ezreal, Corki o Jayce'),
    (r'\bThis item is perfect for AD champions who rely on mana to activate their abilities and auto-attacks\b', 'Perfecto para campeones AD que combinan habilidades y autoataques dependientes de maná'),
    (r'\bThe "Shock" effect allows you to deal bonus physical damage by consuming mana with each auto-attack or ability\b', 'El efecto Choque consume maná para infligir gran daño físico adicional al golpear con habilidades y autoataques'),
    (r'\bOverall, this item provides a huge power spike once completed and is ideal for champions who rely on mana and physical attacks\b', 'Otorga un enorme pico de poder una vez completado, siendo la mejor opción para campeones de maná y daño físico'),
    (r'\bThis item provides a well-rounded set of stats and enhances damage through the combination of abilities and basic attacks\b', 'Otorga estadísticas equilibradas y amplifica el daño combinando habilidades con ataques básicos'),
    (r'\bIt is ideal for champions who frequently weave abilities between attacks and rely on consistent trading\b', 'Ideal para campeones que alternan habilidades y ataques básicos continuamente'),
    (r'\bIt works best on fighters and some mobile carries where versatility, speed, and burst damage in short skirmishes are important\b', 'Brilla en luchadores y tiradores con alta movilidad que buscan versatilidad, velocidad y daño explosivo'),
    (r'\bThis item provides a mix of damage, magic resistance and ability haste, but its core value is the anti-burst passive: when hit by a dangerous burst of magic damage, you instantly gain a strong protective shield and a temporary lifesteal/omnivamp effect that lasts through the fight\b', 'Otorga daño, resistencia mágica y aceleración, pero su mayor valor es su pasiva anti-ráfaga: al recibir daño mágico crítico obtienes un gran escudo y omnivampirismo durante la pelea'),
    (r'\bIt lets you survive big AP detonations and re-enter skirmishes quickly\b', 'Permite sobrevivir al daño explosivo de magos AP y mantenerse firme en la pelea'),
    (r'\bBest for assassins, bruisers and AD champions who need to survive enemy magic burst and power through fights\b', 'Imprescindible para asesinos, colosos y tiradores AD contra amenazas de alto daño mágico'),
    (r'\bThis item is a core survivability tool for AD fighters and assassins\b', 'Herramienta vital de supervivencia para luchadores AD y asesinos'),
    (r'\bIt stores a portion of incoming damage to be taken over time, giving you window to turn the fight\b', 'Convierte parte del daño recibido en sangrado diferido, dándote tiempo para contratacar y sobrevivir'),
    (r'\bScoring a takedown clears the stored damage and restores a large amount of health, making it outstanding for sustained skirmishes and teamfights\b', 'Conseguir un derribo limpia el daño acumulado y restaura una gran cantidad de vida, haciéndolo formidable en peleas prolongadas'),
    (r'\bEssential against high burst AD and AP threats\b', 'Esencial contra amenazas de alto daño explosivo'),
    (r'\bThis item grants high attack speed and critical strike chance with unique burst mobility\b', 'Otorga alta velocidad de ataque y probabilidad de crítico con gran movilidad adicional'),
    (r'\bUpon basic attacking, it grants a stacking movement speed boost and ghosting effect, making it ideal for kiting and continuous chasing in teamfights\b', 'Al atacar obtienes velocidad de movimiento acumulable e ignoras colisión con unidades, ideal para kitear y perseguir enemigos'),
    (r'\bThis item boosts attack speed, critical strike chance, and periodically empowers attacks to fire with increased range and bonus magic damage\b', 'Aumenta la velocidad de ataque, crítico y otorga ataques energizados de mayor alcance con daño mágico'),
    (r'\bIt is perfect for marksmen who need to poke safely from long distances or initiate trades before the enemy can respond\b', 'Perfecto para tiradores que necesitan pokear desde larga distancia o iniciar intercambios con seguridad'),
    (r'\bThis item charges energized attacks that discharge chain lightning across multiple enemies, dealing heavy magic damage\b', 'Carga ataques energizados que desatan rayos encadenados a múltiples enemigos infligiendo gran daño mágico'),
    (r'\bIt greatly accelerates waveclear and adds potent AOE burst to auto-attackers in teamfights\b', 'Acelera notablemente la limpieza de oleadas y aporta daño en área a los tiradores en peleas de equipo'),
    (r'\bThis item grants energized attacks that slow enemies and grant a burst of movement speed\b', 'Otorga ataques energizados que ralentizan al objetivo y te conceden una ráfaga de velocidad de movimiento'),
    (r'\bIdeal for marksmen and assassins needing sticking power and catch potential in early-mid game\b', 'Ideal para tiradores y duelistas que buscan asegurar bajas y ralentizar objetivos clave en el juego temprano y medio'),
    (r'\bThis item reduces your non-ultimate ability cooldowns with every critical strike\b', 'Reduce los enfriamientos de tus habilidades básicas con cada golpe crítico'),
    (r'\bIt allows ability-reliant AD champions like Lucian, Xayah, and Tryndamere to cast their skills in rapid succession during combat\b', 'Permite a campeones que dependen de habilidades y críticos lanzar sus hechizos en rápida sucesión'),
    (r'\bThis item grants percent armor penetration and deals bonus physical damage to enemies with higher maximum health than you\b', 'Otorga penetración de armadura porcentual e inflige daño físico adicional a enemigos con más vida máxima que tú'),
    (r'\bCrucial against tank-heavy compositions\b', 'Crucial contra composiciones con varios tanques o colosos'),
    (r'\bThis item executes enemies below 5% health on hit and grants bonus gold for every kill\b', 'Ejecuta enemigos con menos del 5% de vida al impactar y otorga oro adicional por cada asesinato'),
    (r'\bA lethal snowball item for assassins and crit marksmen to secure kills and build overwhelming leads\b', 'Objeto de efecto bola de nieve letal para asesinos y tiradores de crítico para asegurar asesinatos y ampliar ventajas'),
    (r'\bThis item grants a spell shield that blocks the next enemy ability\b', 'Otorga un escudo de hechizos que bloquea la siguiente habilidad enemiga'),
    (r'\bEssential for assassins and carries facing dangerous crowd control or pick potentials\b', 'Esencial para asesinos y carries contra composiciones con control de masas peligroso o habilidades de iniciación'),
    (r'\bThis item heavily reduces enemy shields upon dealing damage and prevents shield stacking\b', 'Reduce drásticamente los escudos enemigos al infligir daño y contrarresta composiciones con mucho escudo'),
    (r'\bThe ultimate counter against enchanters like Lulu, Janna, Karma, or shield-heavy champions like Shen, Sion, and Sett\b', 'El contraataque definitivo contra soportes de escudos (Lulu, Karma, Janna) y campeones con grandes escudos como Sett, Shen o Sion'),
    (r'\bThis item grants armor penetration and causes your damaging abilities to slow enemies\b', 'Otorga penetración de armadura y hace que tus habilidades de daño ralenticen a los enemigos'),
    (r'\bProvides unmatched kiting and crowd control for AD casters and assassins like Zed, Jayce, and Varus\b', 'Proporciona un kiteo y control insuperables para lanzadores de hechizos AD como Zed, Jayce y Varus'),
    (r'\bThis item empowers your next basic attack after using an ability to deal high percent-max-health damage and heal you for a portion of the damage dealt\b', 'Potencia el siguiente ataque tras usar una habilidad para infligir daño porcentual a la vida máxima y curarte en base al daño infligido'),
    (r'\bThe premier anti-tank bruiser item for champions like Camille, Jax, and Wukong\b', 'El mejor objeto de luchadores contra tanques para campeones como Camille, Jax y Wukong'),
    (r'\bThis item empowers nearby siege and super minions and grants bonus resistances when no allied champions are nearby\b', 'Potencia súbditos de asedio cercanos y otorga resistencias adicionales al estar en solitario'),
    (r'\bThe essential split-pushing tool for top laners to demolish towers and apply isolated map pressure\b', 'La herramienta definitiva de split-push en Top para derribar torres y presionar líneas laterales'),
    (r'\bThis item grants a massive shield and bonus size when taking heavy damage\b', 'Otorga un escudo masivo y tenacidad al recibir gran cantidad de daño'),
    (r'\bCrucial for frontline fighters and bruisers to survive burst focus in teamfights\b', 'Crucial para luchadores de primera línea para resistir el daño concentrado en peleas de equipo'),
    (r'\bThis item causes basic attacks after using an ability to deal bonus damage and restore mana\b', 'Hace que los ataques tras lanzar habilidades inflijan daño adicional y restauren maná'),
    (r'\bEssential for crit casters like Lucian, Corki, and Ezreal to maintain high burst and mana sustainability\b', 'Esencial para tiradores de habilidades como Lucian, Corki o Ezreal para mantener daño explosivo y maná infinito'),
    (r'\bThis item applies Grievous Wounds on physical damage\b', 'Aplica Heridas Graves al infligir daño físico'),
    (r'\bEssential against high sustain fighters like Aatrox, Warwick, and Vladimir\b', 'Esencial contra campeones con alta regeneración o curación como Aatrox, Warwick y Vladimir'),
    (r'\bThis item grants critical strike chance and bonus magic damage upon using abilities\b', 'Otorga probabilidad de crítico y daño mágico adicional tras usar habilidades'),
    (r'\bGreat for hybrid burst carries looking to weave spells and critical strikes\b', 'Excelente para tiradores que combinan habilidades y golpes críticos')
]

print(f"Deep phrase translation rules loaded: {len(DEEP_PHRASES_ES)}")
