import json

en_translations = {
    'Acumula hasta 6 cargas de fuerza adaptable al golpear campeones enemigos. Con el máximo de cargas, otorga vampirismo físico y mágico adicional.': 'Accumulate up to 6 stacks of adaptive force by hitting enemy champions. At max stacks, gain bonus physical and magic vamp.',
    'Alcanzar a un campeón con 3 ataques o habilidades individuales en 3s inflige daño adaptable instantáneo adicional.': 'Hitting a champion with 3 unique attacks or abilities within 3s deals bonus instant adaptive damage.',
    'Los ataques básicos otorgan velocidad de ataque acumulable (hasta 6 veces). Al llegar al máximo, otorga alcance de ataque adicional y velocidad de ataque desbordante.': 'Basic attacks grant stacking attack speed (up to 6 times). At maximum stacks, it grants bonus attack range and lets you exceed the attack speed limit.',
    'Tus ataques y habilidades envían a Aery hacia un objetivo para dañar enemigos o poner un escudo protector a tus aliados.': 'Your attacks and abilities send Aery to a target to damage enemies or shield your allies.',
    'Inmovilizar a un campeón enemigo otorga armadura y resistencia mágica masiva por 2.5s, detonando luego una explosión que inflige daño mágico.': 'Immobilizing an enemy champion grants massive armor and magic resist for 2.5s, then triggers an explosion that deals magic damage.',
    'Dañar a un campeón con una habilidad dispara un cometa hacia su posición que inflige daño mágico adaptativo en área.': 'Damaging a champion with an ability hurls a comet to their location that deals AoE adaptive magic damage.',
    'Mapas aplicables: Wild Rift, Abismo de los Lamentos\n\nOtorga un escudo que absorbe 120 de daño (120 - 560) durante 2,5 s.': 'Applicable Maps: Wild Rift, Howling Abyss\n\nGrants a shield that absorbs 120 (120 - 560) damage for 2.5s.',
    'Mapas aplicables: Wild Rift, Abismo de los Lamentos\n\nExtenúa al campeón enemigo objetivo, lo ralentiza un 35% y reduce su daño un 40% durante 2,5 s. La ralentización decrece mientras dura el efecto.': 'Applicable Maps: Wild Rift, Howling Abyss\n\nExhausts target enemy champion, slowing them by 35% and reducing their damage dealt by 40% for 2.5s. The slow decays over the duration.',
    'Mapas aplicables: Wild Rift y el Abismo de los Lamentos.\n\nElimina las inhabilitaciones (incluidas las de los hechizos) que afectan a tu campeón y le otorga inmunidad a todas las inhabilitaciones durante 0,25 s.': 'Applicable Maps: Wild Rift, Howling Abyss\n\nRemoves all disables (excluding suppressions and airborne) affecting your champion and grants immunity to all disables for 0.25s.',
    'Mapas aplicables: Wild Rift, Abismo de los Lamentos\n\nTeleporta una breve distancia hacia la dirección en la que apunta.': 'Applicable Maps: Wild Rift, Howling Abyss\n\nTeleports a short distance toward the targeted direction.',
    'Mapa aplicable: Grieta\n\nTras canalizar durante 3,5 s, te teleportas a una estructura, campeón o guardián aliado (excepto en las áreas al alcance de los inhibidores enemigos).\nSolo puedes teleportarte a estructuras durante 6 min al comienzo de la partida.': 'Applicable Map: Wild Rift\n\nAfter channeling for 3.5s, teleport to an allied structure, champion, or ward (excluding areas within enemy inhibitor range).\nYou can only teleport to structures for the first 6 minutes of the game.',
    'Mapas disponibles: Abismo de los Lamentos\n\nRestaura un 50% del maná máximo a tu campeón y un 25% a los aliados cercanos.': 'Available Maps: Howling Abyss\n\nRestores 50% of your champion\'s maximum mana and 25% to nearby allies.',
    'Mapa disponible: Abismo de los Lamentos\n\nLanza una bola de nieve que inflige 16 (16-100) de daño, marca a un enemigo y lo revela durante 5 s.\nPuede activarse de nuevo para deslizarse hasta el enemigo marcado, lo que inflige 16 (16-100) de daño al impactar.': 'Available Map: Howling Abyss\n\nThrows a snowball that deals 16 (16-100) damage, marks an enemy, and reveals them for 5s.\nCan be recast to dash to the marked enemy, dealing 16 (16-100) damage on impact.',
    'Daño adicional, amplificación de acumulaciones\n\nAl infligir daño a un campeón que tenga menos del 50% de vida, le infliges daño adaptable y cosechas su alma, lo que aumenta permanentemente el daño de Cosecha oscura en 11.\nDaño de Cosecha oscura: 35 + 11 por alma + 10% adicional DA + 5% PH.\n(20 s de enfriamiento. Se reinicia a 1 s con asesinatos o asistencias).': 'Bonus Damage, Stack Scaling\n\nDamaging a champion below 50% health deals adaptive damage and harvests their soul, permanently increasing Dark Harvest damage by 11.\nDark Harvest Damage: 35 + 11 per soul + 10% bonus AD + 5% AP.\n(20s cooldown. Resets to 1s on takedowns).',
    'Daño explosivo\n\nEn 3 s, golpea a un mismo campeón enemigo con 3 ataques básicos o habilidades para infligirle daño adaptable adicional.\nDaño: 40-210 (nivel) + 10% adicional DA + 5% PH.\nEnfriamiento: 20-13 s (nivel).': 'Burst Damage\n\nHit an enemy champion with 3 unique attacks or abilities within 3s to deal bonus adaptive damage.\nDamage: 40-210 (based on level) + 10% bonus AD + 5% AP.\nCooldown: 20-13s (based on level).',
    'Velocidad de ataque\n\nObtienes velocidad de ataque acumulable al atacar a campeones enemigos. Se acumula hasta 6 veces. Con el máximo de acumulaciones, obtienes alcance adicional y puedes superar el límite de velocidad de ataque.\nCada acumulación aumenta la velocidad de ataque un 6-14% (cuerpo a cuerpo) o un 3,5-8% (a distancia) durante 6 s.\nCon el máximo de acumulaciones, obtienes 25 (cuerpo a cuerpo) o 50 (a distancia) de alcance.': 'Attack Speed\n\nGain stacking attack speed when attacking enemy champions. Stacks up to 6 times. At max stacks, gain bonus attack range and bypass the attack speed limit.\nEach stack increases attack speed by 6-14% (melee) or 3.5-8% (ranged) for 6s.\nAt max stacks, gain 25 (melee) or 50 (ranged) bonus range.',
    'Acumula daño y succión\n\nGolpear a un campeón con ataques o habilidades diferentes otorga acumulaciones de fuerza adaptable. Se acumula hasta 6 veces. Con el máximo de acumulaciones, obtienes omnisucción adicional.\nPor acumulación: 3-5 de daño de ataque o 4-8 de poder de habilidad adicionales durante 6 s.\nMejora al máximo de acumulaciones: 9% (cuerpo a cuerpo) o un 5% (a distancia) de omnisucción adicional.': 'Stacking Damage & Vamp\n\nHitting a champion with separate attacks or abilities grants stacks of Adaptive Force. Stacks up to 6 times. At max stacks, gain bonus omnivamp.\nPer stack: 3-5 bonus AD or 4-8 AP for 6s.\nMax stack bonus: 9% (melee) or 5% (ranged) bonus omnivamp.',
    'Tanque, curación\n\nCada 3 s que pases en combate, se potenciará tu siguiente ataque contra un campeón..\nDaño mágico adicional: 3,3% vida máx.\nCuración: 1,3% vida máx.\nAumento de vida permanente: 10\nCon campeones a distancia, los efectos se reducen un 60%.': 'Tank & Sustain\n\nEvery 3s in combat, your next basic attack on a champion is empowered.\nBonus Magic Damage: 3.3% max health.\nHealing: 1.3% max health.\nPermanent Health Increase: 10.\nEffects are reduced by 60% for ranged champions.',
    'Protección, escudo\n\nProtege a los aliados que se encuentren a 350 unidades de ti y a los aliados que sean objetivos de tus habilidades durante 2,5 s. Si a lo largo de su duración tu aliado o tú recibís más que una pequeña cantidad de daño, ambos obtenéis un escudo durante 1,5 s.\nEnfriamiento: 55-25 s (nivel).\nEscudo: 40-165 (nivel) + 6% adicional vida + 15% PH.\nUmbral de daño: 70-240 de daño recibido (nivel).': 'Protection & Shield\n\nGuard allies within 350 units and allies targeted by your abilities for 2.5s. If you or the guarded ally take a small amount of damage during this time, both gain a shield for 1.5s.\nCooldown: 55-25s (based on level).\nShield: 40-165 (based on level) + 6% bonus health + 15% AP.\nDamage Threshold: 70-240 damage taken (based on level).',
    'Desgaste, protección\n\nTus ataques y habilidades envían a Aery a un objetivo para dañar a los enemigos u otorgar un escudo a los aliados.\nDaño: 15 - 70 (nivel) + 10% adicional DA + 5% PH.\nEscudo: 25 - 120 (nivel) + 10% adicional DA + 5% PH.\nNo se puede enviar a Aery de nuevo hasta que vuelva a ti.': 'Poke & Shield\n\nYour attacks and abilities send Aery to a target to damage enemies or shield allies.\nDamage: 15 - 70 (based on level) + 10% bonus AD + 5% AP.\nShield: 25 - 120 (based on level) + 10% bonus AD + 5% AP.\nAery cannot be sent out again until she returns to you.',
    'Hostigar desde lejos, amplificación de acumulaciones\n\nInfligir daño con una habilidad a un campeón proyecta un cometa hacia su ubicación. Cuando un cometa golpea a un campeón enemigo, aumenta el daño del siguiente.\nDaño: (15 a 100) + (2 × golpes totales a campeones enemigos) + 10% adicional DA + 5% PH.\nEnfriamiento: 16-8 s (nivel).': 'Long-Range Poke, Stack Scaling\n\nDamaging a champion with an ability hurls a comet to their location. Hitting an enemy champion with a comet increases the damage of the next one.\nDamage: (15 to 100) + (2 × total hits on enemy champions) + 10% bonus AD + 5% AP.\nCooldown: 16-8s (based on level).',
    'Control, ralentización\n\nAl inmovilizar a un campeón enemigo, se forman 3 rayos a su alrededor y hielo bajo sus pies durante 3 s, lo que ralentiza a los enemigos que estén en contacto con el hielo. La ralentización se sigue aplicando a los enemigos durante 1,5 s tras abandonar el área helada. Obtienes una capa de hielo protector que te rodea y aumenta tus defensas. Tras un breve lapso de tiempo, el hielo explota, lo que inflige daño mágico a tu alrededor.\nRalentización: (1% de tu vida adicional + 15)%.\nDefensas: 35 + 75% de armadura y resistencia mágica adicionales. Dura 2,5 s.\nDaño mágico: 15–100 (nivel) + 5% vida adicional.\nEnfriamiento: 20 s.': 'Crowd Control & Slow\n\nImmobilizing an enemy champion shoots 3 freezing rays around them and creates ice zones for 3s, slowing enemies inside. The slow persists for 1.5s after leaving the ice. You gain a protective icy layer that increases your defenses. After a short delay, the ice explodes, dealing magic damage around you.\nSlow: (1% of your bonus health + 15)%.\nDefenses: 35 + 75% bonus armor and magic resist. Lasts 2.5s.\nMagic Damage: 15-100 (based on level) + 5% bonus health.\nCooldown: 20s.',
    'Teletransporta a tu campeón una corta distancia hacia la dirección del cursor o apuntada.': 'Teleports your champion a short distance in the aimed direction.',
    'Inflige daño verdadero a lo largo de 5 segundos, reduce la curación del objetivo e inflige Heridas Graves.': 'Deals true damage over 5 seconds, reduces the target\'s healing and applies Grievous Wounds.',
    'Inflige daño verdadero masivo a monstruos de la jungla o súbditos y restaura vida. Evoluciona con campamentos.': 'Deals massive true damage to jungle monsters or minions and restores health. Evolves by taking camps.',
    'Otorga un escudo temporal a tu campeón durante 2 segundos que absorbe daño entrante.': 'Grants a temporary shield to your champion for 2 seconds that absorbs incoming damage.',
    'Reduce la velocidad de movimiento de un campeón enemigo en un 60% y reduce su daño infligido un 40% durante 2.5 segundos.': 'Reduces an enemy champion\'s movement speed by 60% and their damage dealt by 40% for 2.5 seconds.',
    'Aumenta la velocidad de movimiento y permite atravesar unidades durante 8 segundos. Los derribos prolongan su duración.': 'Increases movement speed and lets you pass through units for 8 seconds. Takedowns extend its duration.'
}

pt_translations = {
    'Acumula hasta 6 cargas de fuerza adaptable al golpear campeones enemigos. Con el máximo de cargas, otorga vampirismo físico y mágico adicional.': 'Acumula até 6 cargas de força adaptativa ao atingir campeões inimigos. Com o máximo de cargas, concede vampirismo físico e mágico adicional.',
    'Alcanzar a un campeón con 3 ataques o habilidades individuales en 3s inflige daño adaptable instantáneo adicional.': 'Acertar um campeão com 3 ataques ou habilidades individuais em 3s causa dano adaptativo instantâneo adicional.',
    'Los ataques básicos otorgan velocidad de ataque acumulable (hasta 6 veces). Al llegar al máximo, otorga alcance de ataque adicional y velocidad de ataque desbordante.': 'Ataques básicos concedem velocidade de ataque cumulativa (até 6 vezes). Com o máximo de cargas, concede alcance de ataque adicional e permite ultrapassar o limite de velocidade de ataque.',
    'Tus ataques y habilidades envían a Aery hacia un objetivo para dañar enemigos o poner un escudo protector a tus aliados.': 'Seus ataques e habilidades enviam Aery a um alvo para causar dano a inimigos ou conceder um escudo aos seus aliados.',
    'Inmovilizar a un campeón enemigo otorga armadura y resistencia mágica masiva por 2.5s, detonando luego una explosión que inflige daño mágico.': 'Imobilizar um campeão inimigo concede armadura e resistência mágica massivas por 2,5s, detonando em seguida uma explosão que causa dano mágico.',
    'Dañar a un campeón con una habilidad dispara un cometa hacia su posición que inflige daño mágico adaptativo en área.': 'Causar dano a um campeão com uma habilidade lança um cometa em sua posição que causa dano mágico adaptativo em área.',
    'Mapas aplicables: Wild Rift, Abismo de los Lamentos\n\nOtorga un escudo que absorbe 120 de daño (120 - 560) durante 2,5 s.': 'Mapas aplicáveis: Wild Rift, Howling Abyss\n\nConcede um escudo que absorve 120 (120 - 560) de dano por 2,5s.',
    'Mapas aplicables: Wild Rift, Abismo de los Lamentos\n\nExtenúa al campeón enemigo objetivo, lo ralentiza un 35% y reduce su daño un 40% durante 2,5 s. La ralentización decrece mientras dura el efecto.': 'Mapas aplicáveis: Wild Rift, Howling Abyss\n\nExaure o campeão inimigo alvo, reduzindo sua velocidade em 35% e o dano causado por ele em 40% por 2,5s. A lentidão decai ao longo da duração.',
    'Mapas aplicables: Wild Rift y el Abismo de los Lamentos.\n\nElimina las inhabilitaciones (incluidas las de los hechizos) que afectan a tu campeón y le otorga inmunidad a todas las inhabilitaciones durante 0,25 s.': 'Mapas aplicáveis: Wild Rift, Howling Abyss\n\nRemove todas as desabilitações (excluindo supressões e arremessos) que afetam seu campeão e concede imunidade a todas as desabilitações por 0,25s.',
    'Mapas aplicables: Wild Rift, Abismo de los Lamentos\n\nTeleporta una breve distancia hacia la dirección en la que apunta.': 'Mapas aplicáveis: Wild Rift, Howling Abyss\n\nTeletransporta uma curta distância na direção almejada.',
    'Mapa aplicable: Grieta\n\nTras canalizar durante 3,5 s, te teleportas a una estructura, campeón o guardián aliado (excepto en las áreas al alcance de los inhibidores enemigos).\nSolo puedes teleportarte a estructuras durante 6 min al comienzo de la partida.': 'Mapa aplicável: Wild Rift\n\nApós canalizar por 3,5s, teletransporta-se para uma estrutura, campeão ou sentinela aliada (exceto áreas no alcance do inibidor inimigo).\nVocê só pode se teletransportar para estruturas durante os primeiros 6 minutos de jogo.',
    'Mapas disponibles: Abismo de los Lamentos\n\nRestaura un 50% del maná máximo a tu campeón y un 25% a los aliados cercanos.': 'Mapas disponíveis: Howling Abyss\n\nRestaura 50% da mana máxima do seu campeão e 25% para os aliados próximos.',
    'Mapa disponible: Abismo de los Lamentos\n\nLanza una bola de nieve que inflige 16 (16-100) de daño, marca a un enemigo y lo revela durante 5 s.\nPuede activarse de nuevo para deslizarse hasta el enemigo marcado, lo que inflige 16 (16-100) de daño al impactar.': 'Mapa disponível: Howling Abyss\n\nLança uma bola de neve que causa 16 (16-100) de dano, marca um inimigo e o revela por 5s.\nPode ser reativada para avançar até o inimigo marcado, causando 16 (16-100) de dano ao impacto.',
    'Daño adicional, amplificación de acumulaciones\n\nAl infligir daño a un campeón que tenga menos del 50% de vida, le infliges daño adaptable y cosechas su alma, lo que aumenta permanentemente el daño de Cosecha oscura en 11.\nDaño de Cosecha oscura: 35 + 11 por alma + 10% adicional DA + 5% PH.\n(20 s de enfriamiento. Se reinicia a 1 s con asesinatos o asistencias).': 'Dano Adicional, Amplificação de Acúmulos\n\nCausar dano a um campeão com menos de 50% de vida causa dano adaptativo e colhe sua alma, aumentando permanentemente o dano de Colheita Sombria em 11.\nDano de Colheita Sombria: 35 + 11 por alma + 10% de Dano de Ataque bônus + 5% de Poder de Habilidade.\n(Tempo de Recarga: 20s. Redefine para 1s ao conseguir eliminações ou assistências).',
    'Daño explosivo\n\nEn 3 s, golpea a un mismo campeón enemigo con 3 ataques básicos o habilidades para infligirle daño adaptable adicional.\nDaño: 40-210 (nivel) + 10% adicional DA + 5% PH.\nEnfriamiento: 20-13 s (nivel).': 'Dano Explosivo\n\nAcertar um campeão inimigo com 3 ataques ou habilidades únicas em 3s causa dano adaptativo adicional.\nDano: 40-210 (com base no nível) + 10% de Dano de Ataque bônus + 5% de Poder de Habilidade.\nTempo de Recarga: 20-13s (com base no nível).',
    'Velocidad de ataque\n\nObtienes velocidad de ataque acumulable al atacar a campeones enemigos. Se acumula hasta 6 veces. Con el máximo de acumulaciones, obtienes alcance adicional y puedes superar el límite de velocidad de ataque.\nCada acumulación aumenta la velocidad de ataque un 6-14% (cuerpo a cuerpo) o un 3,5-8% (a distancia) durante 6 s.\nCon el máximo de acumulaciones, obtienes 25 (cuerpo a cuerpo) o 50 (a distancia) de alcance.': 'Velocidade de Ataque\n\nGanha velocidade de ataque cumulativa ao atacar campeões inimigos. Acumula até 6 vezes. Com o máximo de cargas, ganha alcance de ataque adicional e ignora o limite de velocidade de ataque.\nCada carga aumenta a velocidade de ataque em 6-14% (corpo a corpo) ou 3,5-8% (à distância) por 6s.\nCom o máximo de cargas, ganha 25 (corpo a corpo) ou 50 (à distância) de alcance adicional.',
    'Acumula daño y succión\n\nGolpear a un campeón con ataques o habilidades diferentes otorga acumulaciones de fuerza adaptable. Se acumula hasta 6 veces. Con el máximo de acumulaciones, obtienes omnisucción adicional.\nPor acumulación: 3-5 de daño de ataque o 4-8 de poder de habilidad adicionales durante 6 s.\nMejora al máximo de acumulaciones: 9% (cuerpo a cuerpo) o un 5% (a distancia) de omnisucción adicional.': 'Acúmulo de Dano e Vampirismo\n\nAcertar um campeão com ataques ou habilidades separadas concede cargas de Força Adaptativa. Acumula até 6 vezes. Com o máximo de cargas, ganha omnivampirismo adicional.\nPor carga: 3-5 de Dano de Ataque bônus ou 4-8 de Poder de Habilidade por 6s.\nBônus de carga máxima: 9% (corpo a corpo) ou 5% (à distância) de omnivampirismo.',
    'Tanque, curación\n\nCada 3 s que pases en combate, se potenciará tu siguiente ataque contra un campeón..\nDaño mágico adicional: 3,3% vida máx.\nCuración: 1,3% vida máx.\nAumento de vida permanente: 10\nCon campeones a distancia, los efectos se reducen un 60%.': 'Tanque e Sustento\n\nA cada 3s em combate, seu próximo ataque básico em um campeão é fortalecido.\nDano Mágico Adicional: 3,3% da vida máxima.\nCura: 1,3% da vida máxima.\nAumento Permanente de Vida: 10.\nEfeitos são reduzidos em 60% para campeões à distância.',
    'Protección, escudo\n\nProtege a los aliados que se encuentren a 350 unidades de ti y a los aliados que sean objetivos de tus habilidades durante 2,5 s. Si a lo largo de su duración tu aliado o tú recibís más que una pequeña cantidad de daño, ambos obtenéis un escudo durante 1,5 s.\nEnfriamiento: 55-25 s (nivel).\nEscudo: 40-165 (nivel) + 6% adicional vida + 15% PH.\nUmbral de daño: 70-240 de daño recibido (nivel).': 'Proteção e Escudo\n\nProtege aliados em até 350 unidades e aliados alvos de suas habilidades por 2,5s. Se você ou o aliado protegido sofrerem uma pequena quantidade de dano durante esse tempo, ambos ganham um escudo por 1,5s.\nTempo de Recarga: 55-25s (com base no nível).\nEscudo: 40-165 (com base no nível) + 6% de vida bônus + 15% de Poder de Habilidade.\nLimite de Dano: 70-240 de dano sofrido (com base no nível).',
    'Desgaste, protección\n\nTus ataques y habilidades envían a Aery a un objetivo para dañar a los enemigos u otorgar un escudo a los aliados.\nDaño: 15 - 70 (nivel) + 10% adicional DA + 5% PH.\nEscudo: 25 - 120 (nivel) + 10% adicional DA + 5% PH.\nNo se puede enviar a Aery de nuevo hasta que vuelva a ti.': 'Cutucada e Escudo\n\nSeus ataques e habilidades enviam Aery a um alvo para causar dano a inimigos ou conceder um escudo a aliados.\nDano: 15 - 70 (com base no nível) + 10% de Dano de Ataque bônus + 5% de Poder de Habilidade.\nEscudo: 25 - 120 (com base no nível) + 10% de Dano de Ataque bônus + 5% de Poder de Habilidade.\nAery não pode ser enviada novamente até que retorne a você.',
    'Hostigar desde lejos, amplificación de acumulaciones\n\nInfligir daño con una habilidad a un campeón proyecta un cometa hacia su ubicación. Cuando un cometa golpea a un campeón enemigo, aumenta el daño del siguiente.\nDaño: (15 a 100) + (2 × golpes totales a campeones enemigos) + 10% adicional DA + 5% PH.\nEnfriamiento: 16-8 s (nivel).': 'Cutucada de Longo Alcance\n\nCausar dano a um campeão com uma habilidade lança um cometa em sua localização. Acertar um campeão inimigo com um cometa aumenta o dano do próximo.\nDano: (15 a 100) + (2 × total de acertos em campeões inimigos) + 10% de Dano de Ataque bônus + 5% de Poder de Habilidade.\nTempo de Recarga: 16-8s (com base no nível).',
    'Control, ralentización\n\nAl inmovilizar a un campeón enemigo, se forman 3 rayos a su alrededor y hielo bajo sus pies durante 3 s, lo que ralentiza a los enemigos que estén en contacto con el hielo. La ralentización se sigue aplicando a los enemigos durante 1,5 s tras abandonar el área helada. Obtienes una capa de hielo protector que te rodea y aumenta tus defensas. Tras un breve lapso de tiempo, el hielo explota, lo que inflige daño mágico a tu alrededor.\nRalentización: (1% de tu vida adicional + 15)%.\nDefensas: 35 + 75% de armadura y resistencia mágica adicionales. Dura 2,5 s.\nDaño mágico: 15–100 (nivel) + 5% vida adicional.\nEnfriamiento: 20 s.': 'Controle de Grupo e Lentidão\n\nImobilizar um campeão inimigo dispara 3 raios congelantes ao seu redor e cria zonas de gelo por 3s, desacelerando inimigos dentro. A lentidão persiste por 1,5s após sair do gelo. Você ganha uma camada protetora de gelo que aumenta suas defesas. Após um curto intervalo, o gelo explode, causando dano mágico ao seu redor.\nLentidão: (1% da sua vida bônus + 15)%.\nDefesas: 35 + 75% de armadura e resistência mágica bônus. Dura 2,5s.\nDano Mágico: 15-100 (com base no nível) + 5% de vida bônus.\nTempo de Recarga: 20s.',
    'Teletransporta a tu campeón una corta distancia hacia la dirección del cursor o apuntada.': 'Teletransporta seu campeão uma curta distância na direção almejada.',
    'Inflige daño verdadero a lo largo de 5 segundos, reduce la curación del objetivo e inflige Heridas Graves.': 'Causa dano verdadeiro ao longo de 5 segundos, reduz a cura do alvo e aplica Feridas Dolorosas.',
    'Inflige daño verdadero masivo a monstruos de la jungla o súbditos y restaura vida. Evoluciona con campamentos.': 'Causa dano verdadeiro massivo a monstros da selva ou tropas e restaura vida. Evolui ao abater acampamentos.',
    'Otorga un escudo temporal a tu campeón durante 2 segundos que absorbe daño entrante.': 'Concede um escudo temporário ao seu campeão por 2 segundos que absorve dano.',
    'Reduce la velocidad de movimiento de un campeón enemigo en un 60% y reduce su daño infligido un 40% durante 2.5 segundos.': 'Reduz a velocidade de movimento de um campeão inimigo em 60% e seu dano causado em 40% por 2,5 segundos.',
    'Aumenta la velocidad de movimiento y permite atravesar unidades durante 8 segundos. Los derribos prolongan su duración.': 'Aumenta a velocidade de movimento e permite atravessar unidades por 8 segundos. Abates prolongam a duração.'
}

def apply_translations(file_path, trans_dict):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    for k, v in trans_dict.items():
        data[k] = v
        
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

apply_translations('app/src/main/assets/translations_en.json', en_translations)
apply_translations('app/src/main/assets/translations_pt.json', pt_translations)
