import re, json

with open("app/src/main/java/com/example/data/WildRiftItemsData.kt") as f:
    text = f.read()

blocks = text.split("add(WildRiftItem(")
items = []

for idx, b in enumerate(blocks[1:], 1):
    id_m = re.search(r'id\s*=\s*"([^"]+)"', b)
    name_m = re.search(r'name\s*=\s*"([^"]+)"', b)
    cat_m = re.search(r'category\s*=\s*"([^"]+)"', b)
    gold_m = re.search(r'goldCost\s*=\s*(\d+)', b)
    stats_m = re.search(r'stats\s*=\s*"((?:[^"\\]|\\.)*)"', b)
    passive_m = re.search(r'passive\s*=\s*"((?:[^"\\]|\\.)*)"', b, re.DOTALL)
    icon_m = re.search(r'iconUrl\s*=\s*"([^"]+)"', b)
    
    items.append({
        "id": id_m.group(1),
        "name": name_m.group(1),
        "category": cat_m.group(1),
        "goldCost": int(gold_m.group(1)),
        "stats": stats_m.group(1),
        "passive": passive_m.group(1),
        "iconUrl": icon_m.group(1)
    })

print(f"Loaded {len(items)} items for full translation processing.")

# Terminology replacements dictionaries
REPLACE_EN_TO_ES = [
    (r"\bAttack Damage\b", "Daño de Ataque"),
    (r"\bAbility Power\b", "Poder de Habilidad"),
    (r"\bMax Health\b", "Vida Máxima"),
    (r"\bMax Mana\b", "Maná Máximo"),
    (r"\bArmor Penetration\b", "Penetración de Armadura"),
    (r"\bMagic Penetration\b", "Penetración Mágica"),
    (r"\bMagic Resistance\b", "Resistencia Mágica"),
    (r"\bMagic Resist\b", "Resistencia Mágica"),
    (r"\bArmor\b", "Armadura"),
    (r"\bAbility Haste\b", "Aceleración de Habilidad"),
    (r"\bAttack Speed\b", "Velocidad de Ataque"),
    (r"\bMove Speed\b", "Velocidad de Movimiento"),
    (r"\bMovement Speed\b", "Velocidad de Movimiento"),
    (r"\bCritical Rate\b", "Probabilidad de Crítico"),
    (r"\bCritical Strike Chance\b", "Probabilidad de Crítico"),
    (r"\bCritical Strike\b", "Golpe Crítico"),
    (r"\bCritically Strike\b", "asestar un Golpe Crítico"),
    (r"\bCritically Strikes\b", "asestan Golpes Críticos"),
    (r"\bPhysical Vamp\b", "Vampirismo Físico"),
    (r"\bOmni Vamp\b", "Omnivampirismo"),
    (r"\bOmnivamp\b", "Omnivampirismo"),
    (r"\bLifesteal\b", "Robo de Vida"),
    (r"\bPhysical Damage\b", "Daño Físico"),
    (r"\bMagic Damage\b", "Daño Mágico"),
    (r"\bTrue Damage\b", "Daño Verdadero"),
    (r"\bAdaptive Damage\b", "Daño Adaptable"),
    (r"\bAdaptive Force\b", "Fuerza Adaptable"),
    (r"\bCooldown\b", "Enfriamiento"),
    (r"\bShield\b", "Escudo"),
    (r"\bHealth\b", "Vida"),
    (r"\bMana\b", "Maná"),
    (r"\bMana Regen\b", "Regeneración de Maná"),
    (r"\bMana Regeneration\b", "Regeneración de Maná"),
    (r"\bHealth Regen\b", "Regeneración de Vida"),
    (r"\bHealth Regeneration\b", "Regeneración de Vida"),
    (r"\bBase Health Regen\b", "Regeneración de Vida Base"),
    (r"\bBase Mana Regen\b", "Regeneración de Maná Base"),
    (r"\bHeal and Shield Power\b", "Eficacia de Curación y Escudos"),
    (r"\bTenacity\b", "Tenacidad"),
    (r"\bEnemy champions\b", "campeones enemigos"),
    (r"\bEnemy champion\b", "campeón enemigo"),
    (r"\benemy champions\b", "campeones enemigos"),
    (r"\benemy champion\b", "campeón enemigo"),
    (r"\bAllied champions\b", "campeones aliados"),
    (r"\bAllied champion\b", "campeón aliado"),
    (r"\ballied champions\b", "campeones aliados"),
    (r"\ballied champion\b", "campeón aliado"),
    (r"\bChampions\b", "Campeones"),
    (r"\bChampion\b", "Campeón"),
    (r"\bchampions\b", "campeones"),
    (r"\bchampion\b", "campeón"),
    (r"\bMinions\b", "Súbditos"),
    (r"\bminions\b", "súbditos"),
    (r"\bMonsters\b", "Monstruos"),
    (r"\bmonsters\b", "monstruos"),
    (r"\bGrievous Wounds\b", "Heridas Graves"),
    (r"\bSlows\b", "Ralentiza"),
    (r"\bslows\b", "ralentiza"),
    (r"\bSlow\b", "Ralentización"),
    (r"\bslow\b", "ralentización"),
    (r"\bMelee\b", "Cuerpo a cuerpo"),
    (r"\bmelee\b", "cuerpo a cuerpo"),
    (r"\bRanged\b", "A distancia"),
    (r"\branged\b", "a distancia"),
    (r"\bBonus\b", "Adicional"),
    (r"\bbonus\b", "adicional"),
    (r"\bBase\b", "Base"),
    (r"\bbase\b", "base"),
    (r"\bseconds\b", "segundos"),
    (r"\bsecond\b", "segundo"),
    (r"\bStasis\b", "Estasis"),
    (r"\bstasis\b", "estasis"),
    (r"\bResurrect:\b", "Resurrección:"),
    (r"\bBloody:\b", "Sangriento:"),
    (r"\bFervor:\b", "Fervor:"),
    (r"\bEnergized:\b", "Energizado:"),
    (r"\bPower Blitz:\b", "Ráfaga de Poder:"),
    (r"\bWind's Fury:\b", "Furia del Viento:"),
    (r"\bWind Blade:\b", "Espada de Viento:"),
    (r"\bSlice:\b", "Corte:"),
    (r"\bMomentum:\b", "Impulso:"),
    (r"\bRazor:\b", "Cuchilla:"),
    (r"\bNightstalker:\b", "Acechador Nocturno:"),
    (r"\bLast Whisper:\b", "Último Suspiro:"),
    (r"\bSepsis:\b", "Sepsis:"),
    (r"\bSunder:\b", "Hender:"),
    (r"\bRage:\b", "Furia:"),
    (r"\bAwe:\b", "Asombro:"),
    (r"\bMana Charge:\b", "Carga de Maná:"),
    (r"\bShock:\b", "Choque:"),
    (r"\bSpellblade:\b", "Hoja Encantada:"),
    (r"\bValor:\b", "Valor:"),
    (r"\bLifeline:\b", "Línea de Vida:"),
    (r"\bGiant Slayer:\b", "Verdugo de Gigantes:"),
    (r"\bAnnul:\b", "Anular:"),
    (r"\bBanshee's Veil:\b", "Velo de Banshee:"),
    (r"\bStargazer:\b", "Astrónomo:"),
    (r"\bSoulcharged:\b", "Carga Espiritual:"),
    (r"\bImmolate:\b", "Inmolar:"),
    (r"\bCold Steel:\b", "Acero Frío:"),
    (r"\bRock Solid:\b", "Sólido como Roca:"),
    (r"\bTIPS:\b", "💡 Consejos del Coach:"),
    (r"\bThis item is perfect for\b", "Este objeto es ideal para"),
    (r"\bThis item is a staple for\b", "Este objeto es esencial para"),
    (r"\bThis item provides\b", "Este objeto otorga"),
    (r"\bThis item grants\b", "Este objeto otorga"),
    (r"\bThis item turns\b", "Este objeto convierte"),
    (r"\bThis item extends\b", "Este objeto amplía"),
    (r"\bIdeal for\b", "Ideal para"),
    (r"\bIdeal against\b", "Ideal contra"),
    (r"\bPerfect for\b", "Perfecto para"),
    (r"\bBest for\b", "Excelente para"),
    (r"\bIt boosts\b", "Aumenta"),
    (r"\bIt provides\b", "Otorga"),
    (r"\bIt grants\b", "Otorga"),
    (r"\bIt allows you to\b", "Te permite"),
    (r"\bIt is especially effective against\b", "Es especialmente efectivo contra"),
    (r"\bUpon taking lethal damage\b", "Al recibir daño letal"),
    (r"\brestores 50% Health and 100% Mana\b", "restaura un 50% de Vida y un 100% de Maná"),
    (r"\bafter 4 seconds of stasis\b", "tras 4 segundos en estasis"),
    (r"\bMoving and attacking\b", "Moverse y atacar"),
    (r"\bwill generate an Energized Attack\b", "generan un Ataque Energizado"),
    (r"\bDealing physical damage\b", "Infligir daño físico"),
    (r"\bDealing magic damage\b", "Infligir daño mágico"),
    (r"\bDealing damage\b", "Infligir daño"),
    (r"\bdealing physical damage\b", "infligir daño físico"),
    (r"\bdealing magic damage\b", "infligir daño mágico"),
    (r"\bdealing damage\b", "infligir daño"),
    (r"\bUpon taking Magic Damage\b", "Al recibir daño mágico"),
    (r"\bUpon taking Physical Damage\b", "Al recibir daño físico"),
    (r"\bthat would reduce your Health to below\b", "que reduzca tu vida por debajo de"),
    (r"\bthat would reduce your Health below\b", "que reduzca tu vida por debajo de"),
    (r"\bfor 3 seconds\b", "durante 3 segundos"),
    (r"\bfor 4 seconds\b", "durante 4 segundos"),
    (r"\bfor 5 seconds\b", "durante 5 segundos"),
    (r"\bfor 6 seconds\b", "durante 6 segundos"),
    (r"\bfor 2 seconds\b", "durante 2 segundos"),
    (r"\bfor 1 second\b", "durante 1 segundo"),
    (r"\bfor 3s\b", "durante 3s"),
    (r"\bfor 4s\b", "durante 4s"),
    (r"\bfor 5s\b", "durante 5s"),
    (r"\bfor 6s\b", "durante 6s"),
    (r"\bfor 2s\b", "durante 2s"),
    (r"\bfor 1s\b", "durante 1s"),
    (r"\bDuring combat\b", "Durante el combate"),
    (r"\bduring combat\b", "durante el combate"),
    (r"\bIn combat\b", "En combate"),
    (r"\bin combat\b", "en combate"),
    (r"\bout of combat\b", "fuera de combate"),
    (r"\bOut of combat\b", "Fuera de combate")
]

print("Replacement list prepared with", len(REPLACE_EN_TO_ES), "rules.")
