import re

def clean_spanglish(text: str) -> str:
    if not text:
        return text

    # Common Spanglish phrases and direct fixes
    replacements = [
        ("the ataques deals", "los ataques infligen"),
        ("the ataques", "los ataques"),
        ("The first attack aobtienest a Campeón inflige", "El primer ataque contra un campeón inflige"),
        ("aobtienest a Campeón", "contra un campeón"),
        ("aobtienest", "contra"),
        ("infligent to you", "se te inflige"),
        ("infligent", "inflige"),
        ("infligen a deadly daño explosivo with a brief Ralentización", "inflige un letal daño explosivo con una breve ralentización"),
        ("infligen Adicional Daño Físico", "inflige daño físico adicional"),
        ("inflige Adicional Daño Físico", "inflige daño físico adicional"),
        ("deals Adicional Daño Físico", "inflige daño físico adicional"),
        ("deals Adicional physical damage", "inflige daño físico adicional"),
        ("deals Adicional", "inflige daño adicional"),
        ("deals", "inflige"),
        ("dealing", "infligiendo"),
        ("deal", "inflige"),
        ("takes", "recibe"),
        ("taking", "al recibir"),
        ("takes damage", "recibe daño"),
        ("taking lethal damage", "al recibir daño letal"),
        ("damage", "daño"),
        ("physical damage", "daño físico"),
        ("magic damage", "daño mágico"),
        ("true damage", "daño verdadero"),
        ("bonus damage", "daño adicional"),
        ("bonus physical damage", "daño físico adicional"),
        ("bonus magic damage", "daño mágico adicional"),
        ("bonus true damage", "daño verdadero adicional"),
        ("bonus", "adicional"),
        ("Adicional damage in a area", "daño adicional en área"),
        ("damage in a area", "daño en área"),
        ("damage in an area", "daño en área"),
        ("Every 1.75 segundo(s), your next attack inflige", "Cada 1.75 segundos, tu siguiente ataque inflige"),
        ("Every 1.75 segundo(s)", "Cada 1.75 segundos"),
        ("Every 1.75 seconds", "Cada 1.75 segundos"),
        ("Every", "Cada"),
        ("your next attack", "tu siguiente ataque"),
        ("your next basic attack", "tu siguiente ataque básico"),
        ("your next hit", "tu siguiente golpe"),
        ("your next", "tu siguiente"),
        ("your attacks", "tus ataques"),
        ("your basic attacks", "tus ataques básicos"),
        ("your abilities", "tus habilidades"),
        ("your spells", "tus habilidades"),
        ("your champion", "tu campeón"),
        ("your", "tu"),
        ("you gain", "obtienes"),
        ("you receive", "recibes"),
        ("you restore", "restauras"),
        ("you heal", "te curas"),
        ("you deal", "infliges"),
        ("you instantly gain", "obtienes al instante"),
        ("you summon", "invocas"),
        ("you", "tú"),
        ("equal to", "igual a"),
        ("also applies to turrets", "también se aplica a torretas"),
        ("creating a shockwave that inflige", "creando una onda de choque que inflige"),
        ("creating a shockwave that deals", "creando una onda de choque que inflige"),
        ("creating a shockwave", "creando una onda de choque"),
        ("to enemies behind the target", "a los enemigos detrás del objetivo"),
        ("to nearby enemies", "a los enemigos cercanos"),
        ("to enemies", "a los enemigos"),
        ("to enemy champions", "a campeones enemigos"),
        ("behind the target", "detrás del objetivo"),
        ("behind the primary hit", "detrás del impacto principal"),
        ("A distancia Campeones infligen", "Los campeones a distancia infligen"),
        ("A distancia Campeones", "Campeones a distancia"),
        ("A distancia campeones", "Campeones a distancia"),
        ("ranged champions", "campeones a distancia"),
        ("melee champions", "campeones cuerpo a cuerpo"),
        ("melee", "cuerpo a cuerpo"),
        ("ranged", "a distancia"),
        ("Cuerpo a cuerpo", "cuerpo a cuerpo"),
        ("of the damage", "del daño"),
        ("maximum Vida", "Vida Máxima"),
        ("maximum Health", "Vida Máxima"),
        ("max Health", "Vida Máxima"),
        ("current Health", "Vida Actual"),
        ("missing Health", "Vida Faltante"),
        ("Health", "Vida"),
        ("Mana", "Maná"),
        ("Armor", "Armadura"),
        ("Magic Resist", "Resistencia Mágica"),
        ("Ability Haste", "Aceleración de Habilidad"),
        ("Attack Speed", "Velocidad de Ataque"),
        ("Movement Speed", "Velocidad de Movimiento"),
        ("Critical Rate", "Probabilidad de Crítico"),
        ("Critical Strike", "Golpe Crítico"),
        ("Physical Vamp", "Vampirismo Físico"),
        ("Omnivamp", "Omnisucción"),
        ("Omnivampirismo", "Omnisucción"),
        ("Armor Penetration", "Penetración de Armadura"),
        ("Magic Penetration", "Penetración Mágica"),
        ("Cooldown", "Enfriamiento"),
        ("cooldown", "enfriamiento"),
        ("seconds", "segundos"),
        ("second(s)", "segundos"),
        ("second", "segundo"),
        ("stacks", "acumulaciones"),
        ("stack", "acumulación"),
        ("Stacks", "Acumulaciones"),
        ("Stack", "Acumulación"),
        ("charges", "cargas"),
        ("charge", "carga"),
        ("shield", "escudo"),
        ("Shield", "Escudo"),
        ("grants", "otorga"),
        ("granting", "otorgando"),
        ("grant", "otorga"),
        ("provides", "proporciona"),
        ("increases", "aumenta"),
        ("reduces", "reduce"),
        ("decreases", "disminuye"),
        ("restores", "restaura"),
        ("restoring", "restaurando"),
        ("heals", "cura"),
        ("healing", "curación"),
        ("cleanses", "elimina"),
        ("refreshes", "reinicia"),
        ("refresh", "reinicia"),
        ("resets", "reinicia"),
        ("applies", "aplica"),
        ("applying", "aplicando"),
        ("gains", "obtiene"),
        ("gain", "obtiene"),
        ("obtains", "obtiene"),
        ("nearby enemies", "enemigos cercanos"),
        ("nearby allies", "aliados cercanos"),
        ("nearby enemy champions", "campeones enemigos cercanos"),
        ("nearby ally champions", "campeones aliados cercanos"),
        ("nearby", "cercanos"),
        ("target", "objetivo"),
        ("targets", "objetivos"),
        ("enemy", "enemigo"),
        ("enemies", "enemigos"),
        ("champion", "campeón"),
        ("champions", "campeones"),
        ("takedown", "derribo"),
        ("takedowns", "derribos"),
        ("kill or assist", "asesinato o asistencia"),
        ("kills or assists", "asesinatos o asistencias"),
        ("minions", "súbditos"),
        ("minion", "súbdito"),
        ("monsters", "monstruos"),
        ("monster", "monstruo"),
        ("large monster", "monstruo gigante"),
        ("large monsters", "monstruos gigantes"),
        ("epic monster", "monstruo épico"),
        ("epic monsters", "monstruos épicos"),
        ("structures", "estructuras"),
        ("turrets", "torretas"),
        ("turret", "torreta"),
        ("in combat", "en combate"),
        ("out of combat", "fuera de combate"),
        ("after exiting combat", "tras salir de combate"),
        ("after leaving combat", "tras salir de combate"),
        ("over 2 segundos", "a lo largo de 2 segundos"),
        ("over 3 segundos", "a lo largo de 3 segundos"),
        ("over 4 segundos", "a lo largo de 4 segundos"),
        ("over 5 segundos", "a lo largo de 5 segundos"),
        ("over", "a lo largo de"),
        ("for 2 segundos", "durante 2 segundos"),
        ("for 3 segundos", "durante 3 segundos"),
        ("for 4 segundos", "durante 4 segundos"),
        ("for 5 segundos", "durante 5 segundos"),
        ("for 6 segundos", "durante 6 segundos"),
        ("for", "durante"),
        ("with", "con"),
        ("without", "sin"),
        ("against", "contra"),
        ("when", "cuando"),
        ("upon", "al"),
        ("after", "tras"),
        ("before", "antes de"),
        ("while", "mientras"),
        ("during", "durante"),
        ("instead", "en su lugar"),
        ("additional", "adicional"),
        ("Adicional", "adicional"),
        ("bonus", "adicional"),
        ("base AD", "DA base"),
        ("total AD", "DA total"),
        ("bonus AD", "DA adicional"),
        ("base AP", "PH base"),
        ("total AP", "PH total"),
        ("bonus AP", "PH adicional"),
        ("AD", "DA"),
        ("AP", "PH"),
        ("HP", "Vida"),
        ("MR", "RM"),
        ("AH", "Aceleración de Habilidad"),
        ("AS", "Velocidad de Ataque"),
        ("MS", "Velocidad de Movimiento"),
        ("on-hit", "al impacto"),
        ("on hit", "al impacto"),
        ("upon hitting", "al golpear"),
        ("hits an enemy", "golpea a un enemigo"),
        ("hits", "golpea"),
        ("strikes", "golpea"),
        ("attacks", "ataca"),
        ("casts a spell", "lanza una habilidad"),
        ("casts an ability", "lanza una habilidad"),
        ("uses an ability", "usa una habilidad"),
        ("using an ability", "al usar una habilidad"),
        ("using a skill", "al usar una habilidad"),
        ("immobilizing", "al inmovilizar"),
        ("immobilize", "inmovilizar"),
        ("slowing", "al ralentizar"),
        ("slows", "ralentiza"),
        ("slow", "ralentización"),
        ("Ralentiza", "ralentiza"),
        ("Ralentización", "ralentización"),
        ("crowd control", "control de masas"),
        ("airborne", "derribo aéreo"),
        ("stun", "aturdimiento"),
        ("root", "inmovilización"),
        ("silence", "silencio"),
        ("suppression", "supresión"),
        ("blind", "ceguera"),
        ("stealth", "sigilo"),
        ("camuflaje", "camuflaje"),
        ("invisibility", "invisibilidad"),
        ("stasis", "estasis"),
        ("burst damage", "daño explosivo"),
        ("burst", "daño explosivo"),
        ("sustento y curación", "sustento"),
        ("sustento", "sustento"),
        ("sustain", "sustento"),
        ("waveclear", "limpieza de oleadas"),
        ("teamfights", "peleas de equipo"),
        ("teamfight", "pelea de equipo"),
        ("peleas de equipo", "peleas de equipo"),
        ("peleas of equipo", "peleas de equipo"),
        ("laning phase", "fase de líneas"),
        ("early game", "juego temprano"),
        ("mid game", "juego medio"),
        ("late game", "juego tardío"),
        ("power spike", "pico de poder"),
        ("engages", "iniciaciones"),
        ("engage", "iniciación"),
        ("iniciaciónments", "iniciaciones"),
        ("disengage", "desenganche"),
        ("roaming", "rotaciones"),
        ("roam", "rotar"),
        ("roams", "rotaciones"),
        ("snowball", "efecto bola de nieve"),
        ("snowballing", "ampliar ventaja"),
        ("efecto bola de nieveing", "ampliar ventaja"),
        ("peel", "protección"),
        ("kiting", "kiteo"),
        ("kite", "kitear"),
        ("bruisers", "luchadores"),
        ("bruiser", "luchador"),
        ("tanks", "tanques"),
        ("tank", "tanque"),
        ("marksmen", "tiradores"),
        ("marksman", "tirador"),
        ("assassins", "asesinos"),
        ("assassin", "asesino"),
        ("mages", "magos"),
        ("mage", "mago"),
        ("supports", "soportes"),
        ("support", "soporte"),
        ("enchanters", "encantadores"),
        ("enchanter", "encantador"),
        ("duelist", "duelista"),
        ("duelists", "duelistas"),
        ("frontline", "primera línea"),
        ("frontliners", "línea frontal"),
        ("backline", "segunda línea"),
        ("pick-offs", "cazadores individuales"),
        ("picks", "cazas individuales"),
        ("skirmishes", "escaramuzas"),
        ("skirmish", "escaramuza"),
        ("trades", "intercambios"),
        ("trade", "intercambio"),
        ("trading", "intercambios"),
        ("all-in", "enfrentamiento directo"),
        ("poke", "desgaste"),
        ("poking", "desgaste a distancia"),
        ("dive", "inmersión bajo torre"),
        ("diving", "inmersiones bajo torre"),
        ("split push", "empuje dividido"),
        ("split-pushing", "empuje dividido"),
        ("split-push", "empuje dividido"),
        ("splitpush", "empuje dividido"),
        ("Best suited for", "Ideal para"),
        ("Best for", "Ideal para"),
        ("Great for", "Excelente para"),
        ("Ideal for", "Ideal para"),
        ("Perfect for", "Perfecto para"),
        ("Essential for", "Esencial para"),
        ("Key for", "Clave para"),
        ("Mandatory for", "Obligatorio para"),
        ("A great pick for", "Una gran opción para"),
        ("This item is", "Este objeto es"),
        ("This item converts", "Este objeto convierte"),
        ("This item boosts", "Este objeto potencia"),
        ("This item grants", "Este objeto otorga"),
        ("This item provides", "Este objeto proporciona"),
        ("This item enables", "Este objeto permite"),
        ("Este objeto otorga a mix of", "Este objeto otorga una combinación de"),
        ("Este objeto convierte your auto‑attacks into a finisher", "Este objeto convierte tus ataques básicos en un rematador letal"),
        ("Este objeto convierte your ataques básicos into an AOE tool", "Este objeto convierte tus ataques básicos en una herramienta de daño en área"),
        ("Este objeto es ideal para hybrid auto‑attack campeones", "Este objeto es ideal para campeones híbridos de ataques básicos"),
    ]

    res = text
    for old, new in replacements:
        res = res.replace(old, new)

    return res

test_str = "Los ataques infligen Adicional damage in a area\nCleave: Every 1.75 segundo(s), your next attack inflige Adicional Daño Físico equal to 25 + 3% Adicional (also applies to turrets), creating a shockwave that inflige Daño Físico equal to 80 + 10% Adicional to enemies behind the target. A distancia Campeones infligen 75% of the damage."
print('CLEANED:')
print(clean_spanglish(test_str))
