
package com.example.util

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource

val LocalLanguage = compositionLocalOf { "es" }

val translations = mapOf(
    "pt" to mapOf(
        "Elige tu idioma" to "Escolha seu idioma",
        "Automático (Sistema)" to "Padrão do sistema",
        "Español" to "Espanhol",
        "Inglés" to "Inglês",
        "Continuar / Continue" to "Continuar",
        "Firestore & Logs Test Panel" to "Painel de Teste do Firestore e Logs",
        "Add Data" to "Adicionar Dados",
        "Read Data" to "Ler Dados",
        "Delete Data" to "Excluir Dados",
        "Continuar a la App" to "Continuar para o App",
        "Copy Logs" to "Copiar Logs",
        "Logs:" to "Logs:",
        "Permiso de Superposición" to "Permissão de Sobreposição",
        "Para que el asistente inteligente funcione en segundo plano sobre Wild Rift, Android requiere habilitar 'Aparecer encima' (Superposición)." to "Para que o assistente inteligente funcione em segundo plano sobre o Wild Rift, o Android requer a ativação da permissão 'Aparecer sobre outros apps'.",
        "El asistente proporciona lecturas de pantalla y sugerencias en tiempo real sin salir del juego." to "O assistente fornece leituras de tela e sugestões em tempo real sem sair do jogo.",
        "Conceder Permiso" to "Conceder Permissão",
        "Cancelar" to "Cancelar",
        "Base de Datos Meta (Parche 16.16.1)" to "Banco de Dados Meta (Patch 16.16.1)",
        "Campeones" to "Campeões",
        "Sinergias" to "Sinergias",
        "Items" to "Itens",
        "Runas" to "Runas",
        "Ver Guía & Estadísticas en Fuentes Meta:" to "Ver Guia e Estatísticas em Fontes Meta:",
        "Hechizos de Invocador:" to "Feitiços de Invocador:",
        "Árbol de Runas Meta:" to "Árvore de Runas Meta:",
        "Core Items (Obligatorios):" to "Itens Principais (Core):",
        "Objetos Situacionales:" to "Itens Situacionais:",
        "Mejores Sinergias (Composición):" to "Melhores Sinergias (Composição):",
        "Ventaja Contra:" to "Forte Contra:",
        "Débil Contra:" to "Fraco Contra:",
        "Entendido" to "Entendido",
        "Añadir Datos" to "Adicionar Dados",
        "Leer Datos" to "Ler Dados",
        "Borrar Datos" to "Excluir Dados",
        "Copiar Logs" to "Copiar Logs",
        "Logs Copied" to "Logs Copiados",
        "Data Added" to "Dados Adicionados",
        "Data Read Success" to "Dados Lidos com Sucesso",
        "Data Deleted" to "Dados Excluídos",
        "No se pudo cargar la información" to "Não foi possível carregar a informação",
        "Analizando Draft..." to "Analisando Draft...",
        "Activar Asistente (Superposición)" to "Ativar Assistente (Sobreposição)",
        "Buscando composiciones óptimas y counters..." to "Buscando composições ideais e counters...",
        "Asistente Wild Rift" to "Assistente Wild Rift",
        "Cerrar" to "Fechar",
        "Error" to "Erro",
        "Información" to "Informação",
        "MID" to "MID",
        "TOP" to "TOP",
        "JUNGLE" to "JUNGLE",
        "ADC" to "ADC",
        "SUPPORT" to "SUPPORT",
        "Daño" to "Dano",
        "Roles" to "Funções",
        "Buscando composiciones..." to "Buscando composições...",
        "PermisoSuperposicionTexto" to "1. Toque em 'Conceder Permissão'.\n2. Ative o interruptor para o Wild Rift Drafting.\n3. Volte ao aplicativo e pressione ATIVAR.",
        "Línea Main" to "Rota Principal",
        "Segunda Línea" to "Segunda Rota",
        "Rol Autofill" to "Função Preenchimento Automático",
        "Meta & Catálogo de Campeones" to "Meta & Catálogo de Campeões",
        "Tier list, counters, sinergias, runas y objetos" to "Tier list, counters, sinergias, runas e itens",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Assistente Hextech Ativo • Toque na câmera flutuante",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Pressione ATIVAR para iniciar o Assistente Flutuante",
        "★ Mejor Primer Pick Seguro para" to "★ Melhor Primeiro Pick Seguro para",
        "★ Mejor Opción según tu Equipo y el Rival" to "★ Melhor Opção segundo sua Equipe e o Rival",
        "👑 #1 RECOMENDACIÓN BLIND PICK" to "👑 #1 RECOMENDAÇÃO BLIND PICK",
        "👑 #1 MEJOR ELECCIÓN TÁCTICA" to "👑 #1 MELHOR ESCOLHA TÁTICA",
        "Winrate Est.:" to "Taxa de Vitória Est.:",
        "🔮 Runas recomendadas:" to "🔮 Runas recomendadas:",
        "Toca para ver build" to "Toque para ver a build",
        "Otras Opciones Viables para" to "Outras Opções Viáveis para",
        "Alerta de Composición Rival" to "Alerta de Composição Inimiga",
        "Añadir" to "Adicionar",
        "Eliminar" to "Remover",
        "ACTIVAR" to "ATIVAR",
        "DETENER" to "PARAR",
        "Volver" to "Voltar",
        "Reiniciar Draft" to "Reiniciar Draft",
        "Drafting" to "Drafting",
        "Campeones" to "Campeões",
        "Tier List" to "Tier List",
        "Objetos" to "Itens",
        "Runas & Hechizos" to "Runas & Feitiços",
        "Objetivos" to "Objetivos",
        "Fuentes Meta" to "Fontes do Meta",
        "Línea de Barón (Top)" to "Rota do Barão (Top)",
        "Jungla" to "Selva",
        "Línea Central (Mid)" to "Rota Central (Mid)",
        "Línea de Dragón (ADC)" to "Rota do Dragão (ADC)",
        "Soporte (Apoyo)" to "Suporte",
        "Físico" to "Físico",
        "Mágico" to "Mágico",
        "Híbrido / Verdadero" to "Híbrido / Verdadeiro",
        "Físico (AD)" to "Físico (AD)",
        "Mágico (AP)" to "Mágico (AP)",
        "Defensa / Tanque" to "Defesa / Tanque",
        "Utilidad / Soporte" to "Utilidade / Suporte",
        "Botas" to "Botas",
        "Encantamiento" to "Encantamento",
        "Cambiar Rol / Flex Activo:" to "Mudar Função / Flex Ativo:",
        "Toca para alternar" to "Toque para alternar",
        "Análisis Táctico en Wild Rift" to "Análise Tática no Wild Rift",
        "Habilidades de" to "Habilidades de",
        "Pasiva:" to "Passiva:",
        "Habilidad" to "Habilidade",
        "Definitiva:" to "Ultimate:"
    ),
    "en" to mapOf(
        "Elige tu idioma" to "Choose your language",
        "Automático (Sistema)" to "System default",
        "Español" to "Spanish",
        "Inglés" to "English",
        "Continuar / Continue" to "Continue",
        "Firestore & Logs Test Panel" to "Firestore & Logs Test Panel",
        "Add Data" to "Add Data",
        "Read Data" to "Read Data",
        "Delete Data" to "Delete Data",
        "Continuar a la App" to "Continue to App",
        "Copy Logs" to "Copy Logs",
        "Logs:" to "Logs:",
        "Permiso de Superposición" to "Overlay Permission",
        "Para que el asistente inteligente funcione en segundo plano sobre Wild Rift, Android requiere habilitar 'Aparecer encima' (Superposición)." to "For the smart assistant to run in the background over Wild Rift, Android requires enabling the 'Display over other apps' (Overlay) permission.",
        "El asistente proporciona lecturas de pantalla y sugerencias en tiempo real sin salir del juego." to "The assistant provides screen readings and real-time suggestions without leaving the game.",
        "Conceder Permiso" to "Grant Permission",
        "Cancelar" to "Cancel",
        "Base de Datos Meta (Parche 16.16.1)" to "Meta Database (Patch 16.16.1)",
        "Campeones" to "Champions",
        "Sinergias" to "Synergies",
        "Items" to "Items",
        "Runas" to "Runes",
        "Ver Guía & Estadísticas en Fuentes Meta:" to "View Guide & Stats in Meta Sources:",
        "Hechizos de Invocador:" to "Summoner Spells:",
        "Árbol de Runas Meta:" to "Meta Rune Tree:",
        "Core Items (Obligatorios):" to "Core Items:",
        "Objetos Situacionales:" to "Situational Items:",
        "Mejores Sinergias (Composición):" to "Best Synergies (Composition):",
        "Ventaja Contra:" to "Strong Against:",
        "Débil Contra:" to "Weak Against:",
        "Entendido" to "Understood",
        "Añadir Datos" to "Add Data",
        "Leer Datos" to "Read Data",
        "Borrar Datos" to "Delete Data",
        "Copiar Logs" to "Copy Logs",
        "Logs Copied" to "Logs Copied",
        "Data Added" to "Data Added",
        "Data Read Success" to "Data Read Success",
        "Data Deleted" to "Data Deleted",
        "No se pudo cargar la información" to "Could not load information",
        "Analizando Draft..." to "Analyzing Draft...",
        "Activar Asistente (Superposición)" to "Activate Assistant (Overlay)",
        "Buscando composiciones óptimas y counters..." to "Searching for optimal compositions and counters...",
        "Asistente Wild Rift" to "Wild Rift Assistant",
        "Cerrar" to "Close",
        "Error" to "Error",
        "Información" to "Information",
        "MID" to "MID",
        "TOP" to "TOP",
        "JUNGLE" to "JUNGLE",
        "ADC" to "ADC",
        "SUPPORT" to "SUPPORT",
        "Daño" to "Damage",
        "Roles" to "Roles",
        "Buscando composiciones..." to "Searching comps...",
        "PermisoSuperposicionTexto" to "1. Tap 'Grant Permission'.\n2. Enable the switch for Wild Rift Drafting.\n3. Return to the app and press ACTIVATE.",
        "Línea Main" to "Main Role",
        "Segunda Línea" to "Secondary Role",
        "Rol Autofill" to "Autofill Role",
        "Meta & Catálogo de Campeones" to "Meta & Champion Catalog",
        "Tier list, counters, sinergias, runas y objetos" to "Tier list, counters, synergies, runes, and items",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Hextech Assistant Active • Tap the floating camera",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Press ACTIVATE to start the Floating Assistant",
        "★ Mejor Primer Pick Seguro para" to "★ Best Safe First Pick for",
        "★ Mejor Opción según tu Equipo y el Rival" to "★ Best Option for your Team and the Enemy",
        "👑 #1 RECOMENDACIÓN BLIND PICK" to "👑 #1 BLIND PICK RECOMMENDATION",
        "👑 #1 MEJOR ELECCIÓN TÁCTICA" to "👑 #1 BEST TACTICAL CHOICE",
        "Winrate Est.:" to "Est. Winrate:",
        "🔮 Runas recomendadas:" to "🔮 Recommended runes:",
        "Toca para ver build" to "Tap to view build",
        "Otras Opciones Viables para" to "Other Viable Options for",
        "Alerta de Composición Rival" to "Enemy Comp Alert",
        "Añadir" to "Add",
        "Eliminar" to "Remove",
        "ACTIVAR" to "ACTIVATE",
        "DETENER" to "STOP",
        "Volver" to "Back",
        "Reiniciar Draft" to "Reset Draft",
        "Drafting" to "Drafting",
        "Campeones" to "Champions",
        "Tier List" to "Tier List",
        "Objetos" to "Items",
        "Runas & Hechizos" to "Runes & Spells",
        "Objetivos" to "Objectives",
        "Fuentes Meta" to "Meta Sources",
        "Línea de Barón (Top)" to "Baron Lane (Top)",
        "Jungla" to "Jungle",
        "Línea Central (Mid)" to "Mid Lane (Mid)",
        "Línea de Dragón (ADC)" to "Dragon Lane (ADC)",
        "Soporte (Apoyo)" to "Support",
        "Físico" to "Physical",
        "Mágico" to "Magic",
        "Híbrido / Verdadero" to "Hybrid / True",
        "Físico (AD)" to "Physical (AD)",
        "Mágico (AP)" to "Magic (AP)",
        "Defensa / Tanque" to "Defense / Tank",
        "Utilidad / Soporte" to "Utility / Support",
        "Botas" to "Boots",
        "Encantamiento" to "Enchantment",
        "Cambiar Rol / Flex Activo:" to "Change Role / Active Flex:",
        "Toca para alternar" to "Tap to toggle",
        "Análisis Táctico en Wild Rift" to "Tactical Analysis in Wild Rift",
        "Habilidades de" to "Abilities of",
        "Pasiva:" to "Passive:",
        "Habilidad" to "Ability",
        "Definitiva:" to "Ultimate:"
    )
)

@Composable
fun tr(key: String): String {
    val lang = LocalLanguage.current
    if (lang == "es" || lang == "auto") return key
    return translations[lang]?.get(key) ?: key
}

fun trStr(lang: String, key: String): String {
    if (lang == "es" || lang == "auto") return key
    return translations[lang]?.get(key) ?: key
}
