
package com.example.util

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource

val LocalLanguage = compositionLocalOf { "es" }

val translations = mapOf(
    "pt" to mapOf(
        "Acerca De" to "Sobre",
        "Asistente Táctico Wild Rift" to "Assistente Tático Wild Rift",
        "Guía en Tiempo Real para Selección de Campeones" to "Guia em Tempo Real para Seleção de Campeões",
        "1. Acerca del Asistente" to "1. Sobre o Assistente",
        "Edición Móvil" to "Edição Móvel",
        "• Compatibilidad: Diseñado exclusivamente para Wild Rift (habilidades móviles, runas de Wild Rift, balance y objetos móviles)." to "• Compatibilidade: Projetado exclusivamente para o Wild Rift (habilidades móveis, runas do Wild Rift, balanceamento e itens móveis).",
        "• Parche del juego: " to "• Patch do jogo: ",
        "sincronizado con fuentes de balance." to "sincronizado com fontes de balanceamento.",
        "• Motor Hextech: Botón de activación directa con cálculo de composiciones, counters y sinergias." to "• Motor Hextech: Botão de ativação direta com cálculo de composições, counters e sinergias.",
        "• Sistema Flotante: Ventana superpuesta en pantalla con controles táctiles para la fase de selección." to "• Sistema Flutuante: Janela sobreposta na tela com controles sensíveis ao toque para a fase de seleção.",
        "2. Modo de Uso de la Aplicación" to "2. Modo de Uso do Aplicativo",
        "Paso 1: Configura tus Líneas de Juego" to "Passo 1: Configure suas Rotas de Jogo",
        "En la pantalla principal, selecciona tu 'Línea Main', 'Segunda Línea' y 'Rol Autofill' tocando cada tarjeta." to "Na tela principal, selecione sua 'Rota Principal', 'Segunda Rota' e 'Função de Preenchimento Automático' tocando em cada cartão.",
        "Paso 2: Activa el Asistente Flotante" to "Passo 2: Ative o Assistente Flutuante",
        "Pulsa el botón central 'ACTIVAR'. Se desplegará la burbuja flotante en pantalla para acompañarte en tu partida." to "Pressione o botão central 'ATIVAR'. A bolha flutuante será exibida na tela para acompanhá-lo em sua partida.",
        "Paso 3: Selección de Campeones (Champ Select)" to "Passo 3: Seleção de Campeões (Champ Select)",
        "Abre Wild Rift y entra a la fase de selección. Toca el botón flotante en cualquier momento para ver recomendaciones, counters y sinergias tácticas en directo." to "Abra o Wild Rift e entre na fase de seleção. Toque no botão flutuante a qualquer momento para ver recomendações, counters e sinergias táticas ao vivo.",
        "Paso 4: Filtros Automáticos" to "Passo 4: Filtros Automáticos",
        "El asistente prioriza campeones según los roles que hayas configurado en el Paso 1, permitiendo una selección más rápida antes de que se acabe el tiempo." to "O assistente prioriza campeões de acordo com as funções que você configurou no Passo 1, permitindo uma seleção mais rápida antes que o tempo acabe.",
        "3. Interfaz del Asistente (Overlay HUD)" to "3. Interface do Assistente (Overlay HUD)",
        "Pestaña Draft (Icono Lista)" to "Guia Draft (Ícone Lista)",
        "Recomendaciones de picks seguros, counter picks directos y sinergias basándose en tu rol." to "Recomendações de picks seguros, counter picks diretos e sinergias baseadas na sua função.",
        "Pestaña Objetivos (Icono Mapa)" to "Guia Objetivos (Ícone Mapa)",
        "Tiempos de reaparición (spawn) de los monstruos neutrales épicos." to "Tempos de reaparecimento (spawn) dos monstros neutros épicos.",
        "Pestaña Objetos (Icono Espada)" to "Guia Itens (Ícone Espada)",
        "Builds sugeridas para el campeón seleccionado (Core items y situacionales)." to "Builds sugeridas para o campeão selecionado (Core items e situacionais).",
        "Pestaña Runas (Icono Magia)" to "Guia Runas (Ícone Magia)",
        "Página de runas meta óptimas para el campeón sugerido." to "Página de runas meta ideais para o campeão sugerido.",
        "Deslizar para Minimizar" to "Deslizar para Minimizar",
        "Puedes deslizar el panel hacia abajo en cualquier momento para ocultarlo temporalmente sin detener la herramienta." to "Você pode deslizar o painel para baixo a qualquer momento para ocultá-lo temporariamente sem interromper a ferramenta.",
        "Versión del Parche de Wild Rift:" to "Versão do Patch do Wild Rift:",
        "Build y Runas de" to "Build e Runas de",

        "Elige tu idioma" to "Escolha seu idioma",
        "Español" to "Espanhol",
        "Inglés" to "Inglês",
        "Portugués" to "Português",
        "Continuar" to "Continuar",
        "Permiso de Superposición" to "Permissão de Sobreposição",
        "Para que el asistente inteligente funcione en segundo plano sobre Wild Rift, Android requiere habilitar 'Aparecer encima' (Superposición)." to "Para que o assistente inteligente funcione em segundo plano sobre o Wild Rift, o Android requer a ativação da permissão 'Aparecer sobre outros apps'.",
        "El asistente proporciona lecturas de pantalla y sugerencias en tiempo real sin salir del juego." to "O assistente fornece leituras de tela e sugestões em tempo real sem sair do jogo.",
        "Conceder Permiso" to "Conceder Permissão",
        "Cancelar" to "Cancelar",
        "Base de Datos Meta (Parche 16.16.1)" to "Banco de Dados Meta (Patch 16.16.1)",
        "Campeones" to "Campeões",
        "Sinergias" to "Sinergias",
        "Items" to "Itens",
        "Runas" to "Runas",
        "Hechizos de Invocador:" to "Feitiços de Invocador:",
        "Árbol de Runas Meta:" to "Árvore de Runas Meta:",
        "Core Items (Obligatorios):" to "Itens Principais (Core):",
        "Objetos Situacionales:" to "Itens Situacionais:",
        "Mejores Sinergias (Composición):" to "Melhores Sinergias (Composição):",
        "Ventaja Contra:" to "Forte Contra:",
        "Débil Contra:" to "Fraco Contra:",
        "Entendido" to "Entendido",
        "Analizando Draft..." to "Analisando Draft...",
        "Activar Asistente (Superposición)" to "Ativar Assistente (Sobreposição)",
        "Buscando composiciones óptimas y counters..." to "Buscando composições ideais e counters...",
        "Asistente Wild Rift" to "Assistente Wild Rift",
        "Cerrar" to "Fechar",
        "Error" to "Erro",
        "Información" to "Informação",
        "MID" to "MID",
        "TOP" to "TOP",
        "JUNGLE" to "JUNGLE",
        "ADC" to "ADC",
        "SUPPORT" to "SUPPORT",
        "Daño" to "Dano",
        "Roles" to "Funções",
        "Buscando composiciones..." to "Buscando composições...",
        "PermisoSuperposicionTexto" to "1. Toque em 'Conceder Permissão'.\n2. Ative o interruptor para o Wild Rift Drafting.\n3. Volte ao aplicativo e pressione ATIVAR.",
        "Línea Main" to "Rota Principal",
        "Segunda Línea" to "Segunda Rota",
        "Rol Autofill" to "Função Preenchimento Automático",
        "Meta & Catálogo de Campeones" to "Meta & Catálogo de Campeões",
        "Tier list, counters, sinergias, runas y objetos" to "Tier list, counters, sinergias, runas e itens",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Assistente Hextech Ativo • Toque na câmera flutuante",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Pressione ATIVAR para iniciar o Assistente Flutuante",
        "★ Mejor Primer Pick Seguro para" to "★ Melhor Primeiro Pick Seguro para",
        "★ Mejor Opción según tu Equipo y el Rival" to "★ Melhor Opção segundo sua Equipe e o Rival",
        "👑 #1 RECOMENDACIÓN BLIND PICK" to "👑 #1 RECOMENDAÇÃO BLIND PICK",
        "👑 #1 MEJOR ELECCIÓN TÁCTICA" to "👑 #1 MELHOR ESCOLHA TÁTICA",
        "Winrate Est.:" to "Taxa de Vitória Est.:",
        "🔮 Runas recomendadas:" to "🔮 Runas recomendadas:",
        "Toca para ver build" to "Toque para ver a build",
        "Otras Opciones Viables para" to "Outras Opções Viáveis para",
        "Alerta de Composición Rival" to "Alerta de Composição Inimiga",
        "Añadir" to "Adicionar",
        "Eliminar" to "Remover",
        "ACTIVAR" to "ATIVAR",
        "DETENER" to "PARAR",
        "Volver" to "Voltar",
        "Reiniciar Draft" to "Reiniciar Draft",
        "Drafting" to "Drafting",
        "Campeones" to "Campeões",
        "Tier List" to "Tier List",
        "Objetos" to "Itens",
        "Runas & Hechizos" to "Runas & Feitiços",
        "Objetivos" to "Objetivos",

        // Líneas & Roles
        "Línea de Barón" to "Rota do Barão",
        "Jungla" to "Selva",
        "Línea Central" to "Rota do Meio",
        "Línea de Dragón" to "Rota do Dragão",
        "Soporte" to "Suporte",
        "Barón" to "Barão",
        "Central" to "Meio",
        "Dragón" to "Dragão",
        "Físico" to "Físico",
        "Mágico" to "Mágico",
        "Híbrido / Verdadero" to "Híbrido / Verdadeiro",
        "Daño Físico" to "Dano Físico",
        "Poder Mágico" to "Poder Mágico",
        "Defensa" to "Defesa",
        "Utilidad" to "Utilidade",
        "Botas" to "Botas",
        "Encantamiento" to "Encantamento",
        "Botas & Encantamientos" to "Botas & Encantamentos",

        // Hechizos de Invocador
        "Destello" to "Flash",
        "Prender" to "Incendiar",
        "Castigo" to "Golpear",
        "Barrera" to "Barreira",
        "Extenuación" to "Exaustão",
        "Fantasma" to "Fantasma",
        "Curar" to "Curar",
        "Claridad" to "Clareza",
        "Marca / Lanzamiento" to "Marcação / Avanço",

        // Runas
        "Conquistador" to "Conquistador",
        "Matakrakens" to "Mata-Crácens",
        "Cadencia Letal" to "Ritmo Fatal",
        "Electrocutar" to "Eletrocutar",
        "Primer Golpe" to "Primeiro Ataque",
        "Irrupción de Fase" to "Ímpeto Gradual",
        "Agarre del Perpetuo" to "Aperto dos Mortos-Vivos",
        "Réplica" to "Pós-choque",
        "Invocar a Aery" to "Invocar Aery",
        "Aumento Glacial" to "Aprimoramento Glacial",
        "Cometa Arcano" to "Cometa Arcano",
        "Impacto Repentino" to "Impacto Repentino",
        "Quemadura" to "Chamuscar",
        "Colección de Ojos" to "Globos Oculares",
        "Centinela Zombi" to "Sentinela Zumbi",
        "Triunfo" to "Triunfo",
        "Golpe de Gracia" to "Golpe de Misericórdia",
        "Último Esfuerzo" to "Até a Morte",
        "Leyenda: Celeridad" to "Lenda: Espontaneidade",
        "Revestimiento de Huesos" to "Osso Revestido",
        "Segundo Aire" to "Ventos Revigorantes",
        "Condicionamiento" to "Condicionamento",
        "Sobrecrecimiento" to "Crescimento Excessivo",
        "Fuente de Vida" to "Fonte da Vida",
        "Dulces Frutos" to "Fruto Mel",
        "Demolición" to "Demolir",
        "Banda de Flujo de Maná" to "Faixa de Fluxo de Mana",
        "Trascendencia" to "Transcendência",
        "Capa del Nimbo" to "Manto de Nimbus",

        "Runa Clave" to "Runa Essencial",
        "Dominación" to "Dominação",
        "Precisión" to "Precisão",
        "Valor" to "Determinação",
        "Inspiración" to "Inspiração",
        "Brujería" to "Feitiçaria",
        "Todos" to "Todos",
        "Hechizos" to "Feitiços",
        "Runas Clave" to "Runas Essenciais",

        "Cambiar Rol / Flex Activo:" to "Mudar Função / Flex Ativo:",
        "Toca para alternar" to "Toque para alternar",
        "Análisis Táctico en Wild Rift" to "Análise Tática no Wild Rift",
        "Habilidades de" to "Habilidades de",
        "Pasiva:" to "Passiva:",
        "Habilidad" to "Habilidade",
        "Definitiva:" to "Ultimate:",
        "¡Nueva Versión Disponible!" to "Nova Versão Disponível!",
        "Novedades de la actualización:" to "Novidades da atualização:",
        "Descargar e Instalar" to "Baixar e Instalar",
        "Recordarme más tarde" to "Lembrar mais tarde",
        "Actualizaciones de la Aplicación" to "Atualizações do Aplicativo",
        "Buscar Actualizaciones" to "Verificar Atualizações",
        "Comprobando versión..." to "Verificando versão...",
        "¡Tienes la versión más reciente!" to "Você já está na versão mais recente!",
        "Ajustes de Posición" to "Ajustes de Posição",
        "Se pueden seleccionar hasta 2 posiciones" to "Até 2 posições podem ser selecionadas",
        "SOLO NIV. 1" to "SOLO NV. 1",
        "JUNGLA NIV. 1" to "SELVA NV. 1",
        "CENTRAL NIV. 1" to "MEIO NV. 1",
        "DÚO NIV. 1" to "DUO NV. 1",
        "SOPORTE NIV. 1" to "SUPORTE NV. 1"
    ),
    "en" to mapOf(
        "Acerca De" to "About",
        "Asistente Táctico Wild Rift" to "Wild Rift Tactical Assistant",
        "Guía en Tiempo Real para Selección de Campeones" to "Real-Time Guide for Champion Selection",
        "1. Acerca del Asistente" to "1. About the Assistant",
        "Edición Móvil" to "Mobile Edition",
        "• Compatibilidad: Diseñado exclusivamente para Wild Rift (habilidades móviles, runas de Wild Rift, balance y objetos móviles)." to "• Compatibility: Designed exclusively for Wild Rift (mobile skills, Wild Rift runes, balance, and mobile items).",
        "• Parche del juego: " to "• Game patch: ",
        "sincronizado con fuentes de balance." to "synchronized with balance sources.",
        "• Motor Hextech: Botón de activación directa con cálculo de composiciones, counters y sinergias." to "• Hextech Engine: Direct activation button calculating comps, counters, and synergies.",
        "• Sistema Flotante: Ventana superpuesta en pantalla con controles táctiles para la fase de selección." to "• Floating System: Overlay window with touch controls for the drafting phase.",
        "2. Modo de Uso de la Aplicación" to "2. How to Use the App",
        "Paso 1: Configura tus Líneas de Juego" to "Step 1: Configure Your Roles",
        "En la pantalla principal, selecciona tu 'Línea Main', 'Segunda Línea' y 'Rol Autofill' tocando cada tarjeta." to "On the main screen, select your 'Main Role', 'Secondary Role', and 'Autofill Role' by tapping each card.",
        "Paso 2: Activa el Asistente Flotante" to "Step 2: Activate Floating Assistant",
        "Pulsa el botón central 'ACTIVAR'. Se desplegará la burbuja flotante en pantalla para acompañarte en tu partida." to "Press the central 'ACTIVATE' button. The floating bubble will appear on screen to assist you in your match.",
        "Paso 3: Selección de Campeones (Champ Select)" to "Step 3: Champion Selection (Champ Select)",
        "Abre Wild Rift y entra a la fase de selección. Toca el botón flotante en cualquier momento para ver recomendaciones, counters y sinergias tácticas en directo." to "Open Wild Rift and enter champ select. Tap the floating button anytime to see live tactical recommendations, counters, and synergies.",
        "Paso 4: Filtros Automáticos" to "Step 4: Automatic Filters",
        "El asistente prioriza campeones según los roles que hayas configurado en el Paso 1, permitiendo una selección más rápida antes de que se acabe el tiempo." to "The assistant prioritizes champions based on the roles configured in Step 1, allowing faster selection before time runs out.",
        "3. Interfaz del Asistente (Overlay HUD)" to "3. Assistant Interface (Overlay HUD)",
        "Pestaña Draft (Icono Lista)" to "Draft Tab (List Icon)",
        "Recomendaciones de picks seguros, counter picks directos y sinergias basándose en tu rol." to "Safe pick recommendations, direct counter picks, and synergies based on your role.",
        "Pestaña Objetivos (Icono Mapa)" to "Objectives Tab (Map Icon)",
        "Tiempos de reaparición (spawn) de los monstruos neutrales épicos." to "Spawn times of epic neutral monsters.",
        "Pestaña Objetos (Icono Espada)" to "Items Tab (Sword Icon)",
        "Builds sugeridas para el campeón seleccionado (Core items y situacionales)." to "Suggested builds for the selected champion (Core items and situational).",
        "Pestaña Runas (Icono Magia)" to "Runes Tab (Magic Icon)",
        "Página de runas meta óptimas para el campeón sugerido." to "Optimal meta rune page for the suggested champion.",
        "Deslizar para Minimizar" to "Swipe to Minimize",
        "Puedes deslizar el panel hacia abajo en cualquier momento para ocultarlo temporalmente sin detener la herramienta." to "You can swipe the panel down anytime to temporarily hide it without stopping the tool.",
        "Versión del Parche de Wild Rift:" to "Wild Rift Patch Version:",
        "Build y Runas de" to "Build and Runes for",

        "Elige tu idioma" to "Choose your language",
        "Español" to "Spanish",
        "Inglés" to "English",
        "Portugués" to "Portuguese",
        "Continuar" to "Continue",
        "Permiso de Superposición" to "Overlay Permission",
        "Para que el asistente inteligente funcione en segundo plano sobre Wild Rift, Android requiere habilitar 'Aparecer encima' (Superposición)." to "For the smart assistant to run in the background over Wild Rift, Android requires enabling the 'Display over other apps' (Overlay) permission.",
        "El asistente proporciona lecturas de pantalla y sugerencias en tiempo real sin salir del juego." to "The assistant provides screen readings and real-time suggestions without leaving the game.",
        "Conceder Permiso" to "Grant Permission",
        "Cancelar" to "Cancel",
        "Base de Datos Meta (Parche 16.16.1)" to "Meta Database (Patch 16.16.1)",
        "Campeones" to "Champions",
        "Sinergias" to "Synergies",
        "Items" to "Items",
        "Runas" to "Runes",
        "Hechizos de Invocador:" to "Summoner Spells:",
        "Árbol de Runas Meta:" to "Meta Rune Tree:",
        "Core Items (Obligatorios):" to "Core Items:",
        "Objetos Situacionales:" to "Situational Items:",
        "Mejores Sinergias (Composición):" to "Best Synergies (Composition):",
        "Ventaja Contra:" to "Strong Against:",
        "Débil Contra:" to "Weak Against:",
        "Entendido" to "Understood",
        "Analizando Draft..." to "Analyzing Draft...",
        "Activar Asistente (Superposición)" to "Activate Assistant (Overlay)",
        "Buscando composiciones óptimas y counters..." to "Searching for optimal compositions and counters...",
        "Asistente Wild Rift" to "Wild Rift Assistant",
        "Cerrar" to "Close",
        "Error" to "Error",
        "Información" to "Information",
        "MID" to "MID",
        "TOP" to "TOP",
        "JUNGLE" to "JUNGLE",
        "ADC" to "ADC",
        "SUPPORT" to "SUPPORT",
        "Daño" to "Damage",
        "Roles" to "Roles",
        "Buscando composiciones..." to "Searching comps...",
        "PermisoSuperposicionTexto" to "1. Tap 'Grant Permission'.\n2. Enable the switch for Wild Rift Drafting.\n3. Return to the app and press ACTIVATE.",
        "Línea Main" to "Main Role",
        "Segunda Línea" to "Secondary Role",
        "Rol Autofill" to "Autofill Role",
        "Meta & Catálogo de Campeones" to "Meta & Champion Catalog",
        "Tier list, counters, sinergias, runas y objetos" to "Tier list, counters, synergies, runes, and items",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Hextech Assistant Active • Tap the floating camera",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Press ACTIVATE to start the Floating Assistant",
        "★ Mejor Primer Pick Seguro para" to "★ Best Safe First Pick for",
        "★ Mejor Opción según tu Equipo y el Rival" to "★ Best Option for your Team and the Enemy",
        "👑 #1 RECOMENDACIÓN BLIND PICK" to "👑 #1 BLIND PICK RECOMMENDATION",
        "👑 #1 MEJOR ELECCIÓN TÁCTICA" to "👑 #1 BEST TACTICAL CHOICE",
        "Winrate Est.:" to "Est. Winrate:",
        "🔮 Runas recomendadas:" to "🔮 Recommended runes:",
        "Toca para ver build" to "Tap to view build",
        "Otras Opciones Viables para" to "Other Viable Options for",
        "Alerta de Composición Rival" to "Enemy Comp Alert",
        "Añadir" to "Add",
        "Eliminar" to "Remove",
        "ACTIVAR" to "ACTIVATE",
        "DETENER" to "STOP",
        "Volver" to "Back",
        "Reiniciar Draft" to "Reset Draft",
        "Drafting" to "Drafting",
        "Campeones" to "Champions",
        "Tier List" to "Tier List",
        "Objetos" to "Items",
        "Runas & Hechizos" to "Runes & Spells",
        "Objetivos" to "Objectives",

        // Líneas & Roles
        "Línea de Barón" to "Baron Lane",
        "Jungla" to "Jungle",
        "Línea Central" to "Mid Lane",
        "Línea de Dragón" to "Dragon Lane",
        "Soporte" to "Support",
        "Barón" to "Baron",
        "Central" to "Mid",
        "Dragón" to "Dragon",
        "Físico" to "Physical",
        "Mágico" to "Magic",
        "Híbrido / Verdadero" to "Hybrid / True",
        "Daño Físico" to "Physical Damage",
        "Poder Mágico" to "Magic Power",
        "Defensa" to "Defense",
        "Utilidad" to "Utility",
        "Botas" to "Boots",
        "Encantamiento" to "Enchantment",
        "Botas & Encantamientos" to "Boots & Enchantments",

        // Hechizos de Invocador
        "Destello" to "Flash",
        "Prender" to "Ignite",
        "Castigo" to "Smite",
        "Barrera" to "Barrier",
        "Extenuación" to "Exhaust",
        "Fantasma" to "Ghost",
        "Curar" to "Heal",
        "Claridad" to "Clarity",
        "Marca / Lanzamiento" to "Mark / Dash",

        // Runas
        "Conquistador" to "Conqueror",
        "Matakrakens" to "Kraken Slayer",
        "Cadencia Letal" to "Lethal Tempo",
        "Electrocutar" to "Electrocute",
        "Primer Golpe" to "First Strike",
        "Irrupción de Fase" to "Phase Rush",
        "Agarre del Perpetuo" to "Grasp of the Undying",
        "Réplica" to "Aftershock",
        "Invocar a Aery" to "Summon Aery",
        "Aumento Glacial" to "Glacial Augment",
        "Cometa Arcano" to "Arcane Comet",
        "Impacto Repentino" to "Sudden Impact",
        "Quemadura" to "Scorch",
        "Colección de Ojos" to "Eyeball Collection",
        "Centinela Zombi" to "Zombie Ward",
        "Triunfo" to "Triumph",
        "Golpe de Gracia" to "Coup de Grace",
        "Último Esfuerzo" to "Last Stand",
        "Leyenda: Celeridad" to "Legend: Alacrity",
        "Revestimiento de Huesos" to "Bone Plating",
        "Segundo Aire" to "Second Wind",
        "Condicionamiento" to "Conditioning",
        "Sobrecrecimiento" to "Overgrowth",
        "Fuente de Vida" to "Font of Life",
        "Dulces Frutos" to "Sweet Tooth",
        "Demolición" to "Demolish",
        "Banda de Flujo de Maná" to "Manaflow Band",
        "Trascendencia" to "Transcendence",
        "Capa del Nimbo" to "Nimbus Cloak",

        "Runa Clave" to "Keystone Rune",
        "Dominación" to "Domination",
        "Precisión" to "Precision",
        "Valor" to "Resolve",
        "Inspiración" to "Inspiration",
        "Brujería" to "Sorcery",
        "Todos" to "All",
        "Hechizos" to "Spells",
        "Runas Clave" to "Keystones",

        "Cambiar Rol / Flex Activo:" to "Change Role / Active Flex:",
        "Toca para alternar" to "Tap to toggle",
        "Análisis Táctico en Wild Rift" to "Tactical Analysis in Wild Rift",
        "Habilidades de" to "Abilities of",
        "Pasiva:" to "Passive:",
        "Habilidad" to "Ability",
        "Definitiva:" to "Ultimate:",
        "¡Nueva Versión Disponible!" to "New Version Available!",
        "Novedades de la actualización:" to "Update Highlights & Notes:",
        "Descargar e Instalar" to "Download & Install",
        "Recordarme más tarde" to "Remind me later",
        "Actualizaciones de la Aplicación" to "App Updates",
        "Buscar Actualizaciones" to "Check for Updates",
        "Comprobando versión..." to "Checking version...",
        "¡Tienes la versión más reciente!" to "You have the latest version!",
        "Ajustes de Posición" to "Lane Display Setting",
        "Se pueden seleccionar hasta 2 posiciones" to "Up to 2 positions can be displayed",
        "SOLO NIV. 1" to "SOLO LV. 1",
        "JUNGLA NIV. 1" to "JUNGLE LV. 1",
        "CENTRAL NIV. 1" to "MID LV. 1",
        "DÚO NIV. 1" to "DUO LV. 1",
        "SOPORTE NIV. 1" to "SUPPORT LV. 1"
    )
)

@Composable
fun tr(key: String): String {
    val lang = LocalLanguage.current
    if (lang == "es" || lang == "auto") return key
    return translations[lang]?.get(key) ?: key
}

fun trStr(lang: String, key: String): String {
    if (lang == "es" || lang == "auto") return key
    return translations[lang]?.get(key) ?: key
}
