
package com.example.util

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource

val LocalLanguage = compositionLocalOf { "es" }

val translations = mapOf(
    "pt" to mapOf(
        "Línea:" to "Rota:",
        "1er Pick" to "1º Pick",
        "1ª Elección Segura" to "1º Pick (Seguro)",
        "Inicio" to "Início",
        "Catálogo" to "Catálogo",
        "Top" to "Topo",
        "Mid" to "Meio",
        "Jungla" to "Selva",
        "Dúo" to "Duo",
        "Soporte" to "Suporte",
        "Flex en " to "Flex em ",
        "Principal: " to "Principal: ",
        "Flex: " to "Flex: ",
        "Draft" to "Draft",
        "CDs" to "CDs",
        "Daño" to "Dano",
        "Obj" to "Obj",
        "Build" to "Build",
        "Detener Asistente" to "Parar Assistente",
        "Minimizar HUD" to "Minimizar HUD",
        "MEJOR OPCIÓN ABSOLUTA" to "MELHOR OPÇÃO ABSOLUTA",
        "Fijar" to "Fixar",
        "y Ver Runas / Build" to "e Ver Runas / Build",
        "Otras Alternativas en " to "Outras Alternativas em ",
        "Selecciona un campeón para ver su página de runas óptima" to "Selecione um campeão para ver sua página de runas ideal",
        "Fijado" to "Fixado",
        "Página de Runas" to "Página de Runas",
        "Runa Clave Recomendada" to "Runa Essencial Recomendada",
        "Selecciona un campeón para ver sus hechizos de invocador recomendados" to "Selecione um campeão para ver seus feitiços de invocador recomendados",
        "Hechizos & Orden de Habilidades" to "Feitiços e Ordem de Habilidades",
        "Hechizos de Invocador Recomendados" to "Feitiços de Invocador Recomendados",
        "Prioridad de Habilidades" to "Prioridade de Habilidades (Ordem de Evolução)",
        "Maxeo:" to "Maximizar:",
        "Hechizos" to "Feitiços",
        "Runas" to "Runas",
        "Destello" to "Flash",
        "Prender" to "Incendiar (Ignite)",
        "Extenuación" to "Exaustão",
        "Barrera" to "Barreira",
        "Curar" to "Curar",
        "Fantasma" to "Fantasma",
        "Estasis" to "Estase (Zhonya)",
        "Definitiva" to "Ultimate",
        "CD Tracker:" to "CD Tracker:",
        "Rival" to "Inimigo",
        "Enfriamiento:" to "Tempo de Recarga:",
        "restante" to "restante",
        "Base:" to "Base:",
        "¡Listo para usar!" to "Pronto para usar!",
        "Gastado" to "Gasto",
        "Reiniciar Todos" to "Reiniciar Todos",
        "Envía fallos o sugerencias. Se guardarán directamente en la base de datos (con retención automática de 7 días):" to "Envie falhas ou sugestões. Elas serão salvas diretamente no banco de dados (com retenção automática de 7 dias):",
        "Enviar a Base de Datos" to "Enviar para o Banco de Dados",
        "Enviando a Base de Datos..." to "Enviando para o Banco de Dados...",
        "Limpiar Reportes Antiguos (> 7 días)" to "Limpar Relatórios Antigos (> 7 dias)",
        "Módulo de sincronización de la base de datos en la nube. Pulsa el botón para probar la conexión con Supabase o gestionar la retención de reportes." to "Módulo de sincronização do banco de dados na nuvem. Pressione o botão para testar a conexão com Supabase ou gerenciar a retenção de relatórios.",

        "Estado del Servidor" to "Status do Servidor (Supabase)",
        "Módulo de sincronización de la base de datos en la nube. Pulsa el botón para probar la conexión con Supabase." to "Módulo de sincronização do banco de dados na nuvem. Pressione o botão para testar a conexão com Supabase.",
        "Conectando con Supabase..." to "Conectando ao Supabase...",
        "✅ Conexión exitosa. Cliente inicializado." to "✅ Conexão bem-sucedida. Cliente inicializado.",
        "❌ Error de conexión: " to "❌ Erro de conexão: ",
        "Verificar Conexión Supabase" to "Verificar Conexão Supabase",


        // Draft UI Extra
        "Equipo Aliado" to "Equipe Aliada",
        "Equipo Rival" to "Equipe Inimiga",
        "Seleccionar Campeón Aliado" to "Selecionar Campeão Aliado",
        "Seleccionar Campeón Rival" to "Selecionar Campeão Inimigo",

        // Modal de Bienvenida del Parche
        "¡Bienvenidos a Wild Rift Coach!" to "Bem-vindos ao Wild Rift Coach!",
        "Estado del Parche: " to "Status do Patch: ",
        "Estado del Parche:" to "Status do Patch:",
        "Versión del Parche:" to "Versão do Patch:",
        "Versión del Parche de Wild Rift:" to "Versão do Patch do Wild Rift:",
        "Parche" to "Patch",
        "parche" to "patch",
        "Parches" to "Patches",
        "parches" to "patches",
        "Parche 7.2c" to "Patch 7.2c",
        "Parche 7.2b" to "Patch 7.2b",
        "Parche 7.2a" to "Patch 7.2a",
        "Parche 7.2" to "Patch 7.2",
        "1. Compatibilidad y Parche Oficial" to "1. Compatibilidade e Patch Oficial",
        "Ver Notas de Bienvenida y Novedades del Parche" to "Novidades",
        "Novedades" to "Novidades",
        "Runas en Español, Parches y Novedades" to "Runas, Patches e Novidades",
        "Catálogo Completo de Objetos" to "Catálogo Completo de Itens",
        "Sincronizado con wr-meta.com con descripciones, estadísticas y costes actualizados." to "Sincronizado com wr-meta.com com descrições, estatísticas e custos atualizados.",
        "Overlay Flotante Táctico" to "Overlay Flutuante Tático",
        "Asistente en tiempo real durante tu fase de selección y partida en Wild Rift." to "Assistente em tempo real durante a fase de seleção e partida no Wild Rift.",
        "Seguridad y Rendimiento" to "Segurança e Desempenho",
        "Ícono adaptativo optimizado para todas las capas de personalización (Xiaomi/Samsung)." to "Ícone adaptativo otimizado para todas as camadas de personalização (Xiaomi/Samsung).",
        "¡Comenzar / Entendido!" to "Começar / Entendido!",
        "Wild Rift Coach v2.11" to "Wild Rift Coach v2.11",
        "Renombre oficial, contadores dinámicos en catálogos y evaluación táctica de tu pick en tiempo real." to "Renomeação oficial, contadores dinâmicos nos catálogos e avaliação tática do seu pick em tempo real.",
        "Wild Rift Coach v2.0" to "Wild Rift Coach v2.0",
        "Lanzamiento del asistente táctico flotante, catálogo de objetos completo y soporte multi-idioma." to "Lançamento do assistente tático flutuante, catálogo de itens completo e suporte multi-idioma.",
        "Sincronización Oficial" to "Sincronização Oficial",
        "Base de datos de campeones actualizada al parche del juego: " to "Banco de dados de campeões atualizado para o patch do jogo: ",
        "Nuevos ítems de luchador, balances en jungla y adición de evaluación en tiempo real de tu propio campeón durante el draft." to "Novos itens de lutador, balanceamentos na selva e adição de avaliação em tempo real do seu próprio campeão durante o draft.",
        "Ajustes de daño en campeones ADC y mejoras de estabilidad en el catálogo de runas." to "Ajustes de dano em campeões ADC e melhorias de estabilidade no catálogo de runas.",
        "Sincronización oficial del metajuego, estadísticas base y nuevos encantamientos." to "Sincronização oficial do metajogo, estatísticas base e novos encantamentos.",
        "Gran parche de temporada: Rediseño completo de la grieta y adición del asistente overlay flotante." to "Grande patch de temporada: Redesenho completo do mapa e adição do assistente overlay flutuante.",
        "Actual" to "Atual",
        "Cerrar" to "Fechar",

        "¡Bienvenidos!" to "Bem-vindos!",
        "Notas del Nuevo Parche" to "Notas do Novo Patch",
        "• Sincronización automática con: " to "• Sincronização automática com: ",
        "• Análisis táctico actualizado con las últimas estadísticas del meta.\n" to "• Análise tática atualizada com as últimas estatísticas do meta.\n",
        "• Ajustes y corrección de íconos rúnicos." to "• Ajustes e correção de ícones rúnicos.",
        "Organización: Coach de Élite" to "Organização: Coach de Elite (Wild Rift Coach)",
        "Entendido" to "Entendido",
        "El rival tiene alta iniciación de CC con Sett y Vi. Se aconseja desengage, escudos antimagia o tenacidad." to "O inimigo tem alta iniciação de CC com Sett e Vi. É aconselhável desengage, escudos antimagia ou tenacidade.",
        "Caitlyn rival tiene ventaja de rango en carril de Dragón. Prioriza anulación con Viego o agarre con Nautilus/Blitzcrank." to "Caitlyn inimiga tem vantagem de alcance na Rota do Dragão. Priorize anulação com Viego ou puxão com Nautilus/Blitzcrank.",
        "Peligro de asesinos de burst" to "Perigo de assassinos de burst",
        "Imprescindible Zhonya/Estasis y CC garantizado (Lulu, Malzahar, Nautilus)." to "Imprescindível Zhonya/Estase e CC garantido (Lulu, Malzahar, Nautilus).",
        "Composición rival pesada" to "Composição inimiga pesada",
        "Requiere daño verdadero y % vida máxima." to "Requer dano verdadeiro e % de vida máxima.",
        "Morgana o Janna" to "Morgana ou Janna",
        "Nautilus o Viego" to "Nautilus ou Viego",
        "Lulu, Nautilus o Zhonya" to "Lulu, Nautilus ou Zhonya",
        "Vayne, Sett, Gwen o Liandry" to "Vayne, Sett, Gwen ou Liandry",
        "Conquistador (Precisión)" to "Conquistador (Precisão)",
        "Táctico" to "Tático",
        "Daño Físico" to "Dano Físico",
        "Daño Mágico" to "Dano Mágico",
        "Daño Verdadero" to "Dano Verdadeiro",
        "Tanque" to "Tanque",
        "Mago" to "Mago",
        "Luchador" to "Lutador",
        "Asesino" to "Assassino",
        "Tirador" to "Atirador",
        "Soporte" to "Suporte",
        "Top" to "Topo",
        "Jungla" to "Caçador",
        "Medio" to "Meio",
        "Dúo" to "Atirador",
        "Línea de Barón" to "Rota do Barão",
        "Línea de Medio" to "Rota do Meio",
        "Línea de Dragón" to "Rota do Dragão",
        "💡 Si tu dispositivo muestra 'conflicto con un paquete', desinstala la versión anterior de tu teléfono una sola vez e instala la nueva APK (ocurre por cambio de firma de depurado a producción)." to "💡 Se o seu dispositivo mostrar 'conflito de pacote', desinstale a versão anterior do seu telefone uma vez e instale o novo APK (ocorre devido à alteração da assinatura de depuração para produção)."
,
        "Acerca De" to "Sobre",
        "Asistente Táctico Wild Rift" to "Assistente Tático Wild Rift",
        "Guía en Tiempo Real para Selección de Campeones" to "Guia em Tempo Real para Seleção de Campeões",
        "1. Acerca del Asistente" to "1. Sobre o Assistente",
        "Edición Móvil" to "Edição Móvel",
        "• Compatibilidad: Diseñado exclusivamente para Wild Rift (habilidades móviles, runas de Wild Rift, balance y objetos móviles)." to "• Compatibilidade: Projetado exclusivamente para o Wild Rift (habilidades móveis, runas do Wild Rift, balanceamento e itens móveis).",
        "• Parche del juego: " to "• Patch do jogo: ",
        "sincronizado con fuentes de balance." to "sincronizado com fontes de balanceamento.",
        "• Motor Hextech: Botón de activación directa con cálculo de composiciones, counters y sinergias." to "• Motor Hextech: Botão de ativação direta com cálculo de composições, counters e sinergias.",
        "• Sistema Flotante: Ventana superpuesta en pantalla con controles táctiles para la fase de selección." to "• Sistema Flutuante: Janela sobreposta na tela com controles sensíveis ao toque para a fase de seleção.",
        "2. Modo de Uso de la Aplicación" to "2. Modo de Uso do Aplicativo",
        "Paso 1: Configura tus Líneas de Juego" to "Passo 1: Configure suas Rotas de Jogo",
        "En la pantalla principal, selecciona tu 'Línea Main', 'Segunda Línea' y 'Rol Autofill' tocando cada tarjeta." to "Na tela principal, selecione sua 'Rota Principal', 'Segunda Rota' e 'Função de Preenchimento Automático' tocando em cada cartão.",
        "Paso 2: Activa el Asistente Flotante" to "Passo 2: Ative o Assistente Flutuante",
        "Pulsa el botón central 'ACTIVAR'. Se desplegará la burbuja flotante en pantalla para acompañarte en tu partida." to "Pressione o botão central 'ATIVAR'. A bolha flutuante será exibida na tela para acompanhá-lo em sua partida.",
        "Paso 3: Selección de Campeones" to "Passo 3: Seleção de Campeões (Champ Select)",
        "Abre Wild Rift y entra a la fase de selección. Toca el botón flotante en cualquier momento para ver recomendaciones, counters y sinergias tácticas en directo." to "Abra o Wild Rift e entre na fase de seleção. Toque no botão flutuante a qualquer momento para ver recomendações, counters e sinergias táticas ao vivo.",
        "Paso 4: Filtros Automáticos" to "Passo 4: Filtros Automáticos",
        "El asistente prioriza campeones según los roles que hayas configurado en el Paso 1, permitiendo una selección más rápida antes de que se acabe el tiempo." to "O assistente prioriza campeões de acordo com as funções que você configurou no Passo 1, permitindo uma seleção mais rápida antes que o tempo acabe.",
        "3. Interfaz del Asistente" to "3. Interface do Assistente (Overlay HUD)",
        "Pestaña Draft" to "Guia Draft (Ícone Lista)",
        "Recomendaciones de picks seguros, counter picks directos y sinergias basándose en tu rol." to "Recomendações de picks seguros, counter picks diretos e sinergias baseadas na sua função.",
        "Pestaña Objetivos" to "Guia Objetivos (Ícone Mapa)",
        "Tiempos de reaparición (spawn) de los monstruos neutrales épicos." to "Tempos de reaparecimento (spawn) dos monstros neutros épicos.",
        "Pestaña Objetos" to "Guia Itens (Ícone Espada)",
        "Builds sugeridas para el campeón seleccionado (Core items y situacionales)." to "Builds sugeridas para o campeão selecionado (Core items e situacionais).",
        "Pestaña Runas" to "Guia Runas (Ícone Magia)",
        "Página de runas meta óptimas para el campeón sugerido." to "Página de runas meta ideais para o campeão sugerido.",
        "Deslizar para Minimizar" to "Deslizar para Minimizar",
        "Puedes deslizar el panel hacia abajo en cualquier momento para ocultarlo temporalmente sin detener la herramienta." to "Você pode deslizar o painel para baixo a qualquer momento para ocultá-lo temporariamente sem interromper a ferramenta.",
        "Versión del Parche de Wild Rift:" to "Versão do Patch do Wild Rift:",
        "Build y Runas de" to "Build e Runas de",
        "Básicos" to "Básicos",
        "Nivel Medio" to "Nível Médio",
        "Botas N2" to "Botas N2",
        "Botas N3" to "Botas N3",
        "Encantamientos" to "Encantamentos",
        "ÍTEMS BÁSICOS" to "ITENS BÁSICOS (BASIC ITEMS)",
        "ÍTEMS DE NIVEL MEDIO" to "ITENS DE NÍVEL MÉDIO (MID TIER)",
        "DAÑO FÍSICO" to "DANO FÍSICO (PHYSICAL DAMAGE)",
        "DAÑO MÁGICO" to "DANO MÁGICO (MAGIC DAMAGE)",
        "DEFENSA" to "DEFESA (DEFENSIVE ITEMS)",
        "SOPORTE" to "SUPORTE (SUPPORT ITEMS)",
        "BOTAS NIVEL 2" to "BOTAS NÍVEL 2 (BOOTS TIER 2)",
        "BOTAS NIVEL 3" to "BOTAS NÍVEL 3 (BOOTS TIER 3)",
        "ENCANTAMIENTOS Y ACTIVOS" to "ENCANTAMENTOS E ATIVOS (ACTIVE ITEMS)",
        "Cuadrícula" to "Grade",
        "Detallado" to "Detalhado",
        "Buscar objeto por nombre o estadísticas..." to "Buscar item por nome ou atributos...",
        "Estadísticas:" to "Atributos:",
        "Efecto / Pasiva:" to "Efeito / Passiva:",
        "Coste:" to "Custo:",
        "Oro" to "Ouro",

        "Elige tu idioma" to "Escolha seu idioma",
        "Español" to "Espanhol",
        "Inglés" to "Inglês",
        "Portugués" to "Português",
        "Continuar" to "Continuar",
        "Permiso de Superposición" to "Permissão de Sobreposição",
        "Para que el asistente inteligente funcione en segundo plano sobre Wild Rift, Android requiere habilitar 'Aparecer encima' (Superposición)." to "Para que o assistente inteligente funcione em segundo plano sobre o Wild Rift, o Android requer a ativação da permissão 'Aparecer sobre outros apps'.",
        "El asistente proporciona lecturas de pantalla y sugerencias en tiempo real sin salir del juego." to "O assistente fornece leituras de tela e sugestões em tempo real sem sair do jogo.",
        "Conceder Permiso" to "Conceder Permissão",
        "Cancelar" to "Cancelar",
        "Base de Datos Tier List (Parche 16.16.1)" to "Banco de Dados Tier List (Patch 16.16.1)",
        "Campeones" to "Campeões",
        "Sinergias" to "Sinergias",
        "Items" to "Itens",
        "Runas" to "Runas",
        "Hechizos de Invocador:" to "Feitiços de Invocador:",
        "Árbol de Runas:" to "Árvore de Runas:",
        "Objetos Básicos:" to "Itens Principais (Core):",
        "Objetos Situacionales:" to "Itens Situacionais:",
        "Mejores Sinergias:" to "Melhores Sinergias (Composição):",
        "Ventaja Contra:" to "Forte Contra:",
        "Débil Contra:" to "Fraco Contra:",
        "Entendido" to "Entendido",
        "Analizando Draft..." to "Analisando Draft...",
        "Activar Asistente" to "Ativar Assistente (Sobreposição)",
        "Buscando composiciones óptimas y counters..." to "Buscando composições ideais e counters...",
        "Asistente Wild Rift" to "Assistente Wild Rift",
        "Cerrar" to "Fechar",
        "Error" to "Erro",
        "Información" to "Informação",
        "MID" to "MID",
        "TOP" to "TOP",
        "JUNGLE" to "JUNGLE",
        "ADC" to "ADC",
        "SUPPORT" to "SUPPORT",
        "Daño" to "Dano",
        "Roles" to "Funções",
        "Buscando composiciones..." to "Buscando composições...",
        "PermisoSuperposicionTexto" to "1. Toque em 'Conceder Permissão'.\n2. Ative o interruptor para o Wild Rift Coach.\n3. Volte ao aplicativo e pressione ATIVAR.",
        "Línea Main" to "Rota Principal",
        "Segunda Línea" to "Segunda Rota",
        "Rol Autofill" to "Função Preenchimento Automático",
        "Tier List & Catálogo de Campeones" to "Tier List & Catálogo de Campeões",
        "Tier list, counters, sinergias, runas y objetos" to "Tier list, counters, sinergias, runas e itens",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Assistente Hextech Ativo • Toque na câmera flutuante",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Pressione ATIVAR para iniciar o Assistente Flutuante",
        "★ Mejor Primer Pick Seguro para" to "★ Melhor Primeiro Pick Seguro para",
        "★ Mejor Opción según tu Equipo y el Rival" to "★ Melhor Opção segundo sua Equipe e o Rival",
        "👑 #1 RECOMENDACIÓN BLIND PICK" to "👑 #1 RECOMENDAÇÃO BLIND PICK",
        "👑 #1 MEJOR ELECCIÓN TÁCTICA" to "👑 #1 MELHOR ESCOLHA TÁTICA",
        "Winrate Est.:" to "Taxa de Vitória Est.:",
        "🔮 Runas recomendadas:" to "🔮 Runas recomendadas:",
        "Toca para ver build" to "Toque para ver a build",
        "Otras Opciones Viables para" to "Outras Opções Viáveis para",
        "Alerta de Composición Rival" to "Alerta de Composição Inimiga",
        "Añadir" to "Adicionar",
        "Eliminar" to "Remover",
        "ACTIVAR" to "ATIVAR",
        "DETENER" to "PARAR",
        "Volver" to "Voltar",
        "Reiniciar Draft" to "Reiniciar Draft",
        "Drafting" to "Drafting",
        "Campeones" to "Campeões",
        "Tier List" to "Tier List",
        "Objetos" to "Itens",
        "Ítems" to "Itens",
        "Ítem" to "Item",
        "Runas" to "Runas",
        "Hechizos" to "Feitiços",
        "Runas & Hechizos" to "Runas & Feitiços",
        "Objetivos" to "Objetivos",
        "Buscar runa..." to "Buscar runa...",
        "Buscar hechizo..." to "Buscar feitiço...",
        "Runas Wild Rift" to "Runas do Wild Rift",
        "Hechizos de Invocador" to "Feitiços de Invocador",
        "Runas Clave" to "Runas Chave",
        "Dominación" to "Dominação",
        "Precisión" to "Precisão",
        "Valor" to "Determinação",
        "Inspiración" to "Inspiração",
        "Brujería" to "Feitiçaria",
        "Combate & Daño" to "Combate e Dano",
        "Movilidad & Utilidad" to "Mobilidade e Utilidade",
        "Build de" to "Build de",
        "Runas de" to "Runas de",
        "Hechizos de" to "Feitiços de",
        "Habilidades" to "Habilidades",
        "Cambiar" to "Mudar",

        // Líneas & Roles
        "Línea de Barón" to "Rota do Barão",
        "Jungla" to "Selva",
        "Línea Central" to "Rota do Meio",
        "Línea de Dragón" to "Rota do Dragão",
        "Soporte" to "Suporte",
        "Barón" to "Barão",
        "Central" to "Meio",
        "Dragón" to "Dragão",
        "Físico" to "Físico",
        "Mágico" to "Mágico",
        "Híbrido / Verdadero" to "Híbrido / Verdadeiro",
        "Daño Físico" to "Dano Físico",
        "Poder Mágico" to "Poder Mágico",
        "Defensa" to "Defesa",
        "Utilidad" to "Utilidade",
        "Botas" to "Botas",
        "Encantamiento" to "Encantamento",
        "Botas & Encantamientos" to "Botas & Encantamentos",

        // Hechizos de Invocador
        "Destello" to "Flash",
        "Prender" to "Incendiar",
        "Castigo" to "Golpear",
        "Barrera" to "Barreira",
        "Extenuación" to "Exaustão",
        "Fantasma" to "Fantasma",
        "Curar" to "Curar",
        "Claridad" to "Clareza",
        "Marca / Lanzamiento" to "Marcação / Avanço",

        // Runas
        "Conquistador" to "Conquistador",
        "Matakrakens" to "Mata-Crácens",
        "Cadencia Letal" to "Ritmo Fatal",
        "Electrocutar" to "Eletrocutar",
        "Primer Golpe" to "Primeiro Ataque",
        "Irrupción de Fase" to "Ímpeto Gradual",
        "Agarre del Perpetuo" to "Aperto dos Mortos-Vivos",
        "Réplica" to "Pós-choque",
        "Invocar a Aery" to "Invocar Aery",
        "Aumento Glacial" to "Aprimoramento Glacial",
        "Cometa Arcano" to "Cometa Arcano",
        "Impacto Repentino" to "Impacto Repentino",
        "Quemadura" to "Chamuscar",
        "Colección de Ojos" to "Globos Oculares",
        "Centinela Zombi" to "Sentinela Zumbi",
        "Triunfo" to "Triunfo",
        "Golpe de Gracia" to "Golpe de Misericórdia",
        "Último Esfuerzo" to "Até a Morte",
        "Leyenda: Celeridad" to "Lenda: Espontaneidade",
        "Revestimiento de Huesos" to "Osso Revestido",
        "Segundo Aire" to "Ventos Revigorantes",
        "Condicionamiento" to "Condicionamento",
        "Sobrecrecimiento" to "Crescimento Excessivo",
        "Fuente de Vida" to "Fonte da Vida",
        "Dulces Frutos" to "Fruto Mel",
        "Demolición" to "Demolir",
        "Banda de Flujo de Maná" to "Faixa de Fluxo de Mana",
        "Trascendencia" to "Transcendência",
        "Capa del Nimbo" to "Manto de Nimbus",

        "Runa Clave" to "Runa Essencial",
        "Dominación" to "Dominação",
        "Precisión" to "Precisão",
        "Valor" to "Determinação",
        "Inspiración" to "Inspiração",
        "Brujería" to "Feitiçaria",
        "Todos" to "Todos",
        "Hechizos" to "Feitiços",
        "Runas Clave" to "Runas Essenciais",

        "Cambiar Rol / Flex Activo:" to "Mudar Função / Flex Ativo:",
        "Toca para alternar" to "Toque para alternar",
        "Análisis Táctico en Wild Rift" to "Análise Tática no Wild Rift",
        "Habilidades de" to "Habilidades de",
        "Pasiva:" to "Passiva:",
        "Habilidad" to "Habilidade",
        "Definitiva:" to "Ultimate:",
        "¡Nueva Versión Disponible!" to "Nova Versão Disponível!",
        "Novedades de la actualización:" to "Novidades da atualização:",
        "Descargar e Instalar" to "Baixar e Instalar",
        "Recordarme más tarde" to "Lembrar mais tarde",
        "Actualizaciones de la Aplicación" to "Atualizações do Aplicativo",
        "Buscar Actualizaciones" to "Verificar Atualizações",
        "Comprobando versión..." to "Verificando versão...",
        "¡Tienes la versión más reciente!" to "Você já está na versão mais recente!",
        "Ajustes de Posición" to "Ajustes de Posição",
        "Se pueden seleccionar hasta 2 posiciones" to "Até 2 posições podem ser selecionadas",
        "SOLO" to "TOP",
        "TOP" to "TOP",
        "Top" to "Top",
        "Barón" to "Barão",
        "BARÓN" to "BARÃO",
        "JUNGLA" to "SELVA",
        "Jungla" to "Selva",
        "CENTRAL" to "MEIO",
        "MID" to "MID",
        "Mid" to "Mid",
        "DÚO" to "DUO",
        "Dúo" to "Duo",
        "ADC" to "ADC",
        "SOPORTE" to "SUPORTE",
        "Soporte" to "Suporte",
        "Todos los Roles" to "Todas as Funções",
        "Todas las Líneas" to "Todas as Rotas",
        "Buscar campeón por nombre o habilidad..." to "Buscar campeão por nome ou habilidade...",
        "Buscar objeto por nombre o estadísticas..." to "Buscar item por nome ou atributos...",
        "Buscar campeón fijado..." to "Buscar campeão fixado...",
        "Buscar campeón..." to "Buscar campeão...",
        "Buscar objeto situacional (ej. Heridas, Zhonya)..." to "Buscar item situacional (ex. Corta-cura, Zhonya)...",
        "Monstruos Épicos & Tiempos de Aparición" to "Monstros Épicos e Tempos de Renascimento",
        "Conocer los tiempos exactos de aparición en Wild Rift asegura la victoria de tu equipo:" to "Conhecer os tempos exatos no Wild Rift garante a vitória da sua equipe:",
        "Escanear" to "Escanear",
        "Coste" to "Custo",
        "Oro" to "Ouro",
        "Reaparición" to "Renascimento",
        "Reaparición:" to "Renascimento:",
        "⚡ Toca para ver info" to "⚡ Toque para ver detalhes",
        "Selecciona un campeón para ver su página de runas óptima" to "Selecione um campeão para ver a página de runas ideal",
        "Selecciona un campeón para ver sus hechizos de invocador recomendados" to "Selecione um campeão para ver os feitiços recomendados",
        "Daño Físico" to "Dano Físico",
        "Daño Mágico" to "Dano Mágico",
        "Poder Mágico" to "Poder Mágico",
        "Defensa" to "Defesa",
        "Soporte" to "Suporte",
        "Objetos Activos" to "Itens Ativos",
        "Botas Nivel 2" to "Botas Nível 2",
        "Botas Nivel 3" to "Botas Nível 3",
        "Nivel Medio" to "Nível Médio",
        "Nivel Básico" to "Nível Básico",
        "Botas & Encantamientos" to "Botas e Encantamentos",
        "Físico" to "Físico",
        "Mágico" to "Mágico",
        "Híbrido / Verdadero" to "Híbrido / Verdadeiro",
        "Principal:" to "Principal:",
        "Flex:" to "Flex:",
        "Objetos Clave (Build Recomendada)" to "Itens Principais (Build Recomendada)",
        "Objetos Básicos:" to "Itens Principais (Obrigatórios):",
        "Objetos Situacionales:" to "Itens Situacionais:",
        "¿Por qué comprar este objeto?" to "Por que comprar este item?",
        "Efectivo contra:" to "Eficaz contra:",
        "Efecto clave:" to "Efeito chave:",
        "Consejo de compra:" to "Dica de compra:",
        "Tasa de Victoria" to "Taxa de Vitória",
        "Tasa de Selección" to "Taxa de Escolha",
        "Tasa de Bloqueo" to "Taxa de Banimento",
        "Win Rate" to "Taxa de Vitória",
        "Pick Rate" to "Taxa de Escolha",
        "Ban Rate" to "Taxa de Banimento",
        "Hechizos de Invocador" to "Feitiços de Invocador",
        "Runas" to "Runas",
        "Árbol de Runas" to "Árvore de Runas",
        "Cambiar Línea / Rol Activo:" to "Mudar Rota / Função Ativa:",
        "Línea de Barón" to "Rota do Barão",
        "Línea Central" to "Rota do Meio",
        "Línea de Dragón" to "Rota do Dragão",

        // Reportes & Sugerencias
        "Reportes & Sugerencias" to "Relatórios e Sugestões",
        "Reporta fallos o envía sugerencias para mejorar el asistente:" to "Relate bugs ou envie sugestões para melhorar o assistente:",
        "Reportar Bug" to "Reportar Bug",
        "Bug / Error" to "Bug / Erro",
        "Sugerencia" to "Sugestão",
        "Idea / Mejora" to "Ideia / Melhoria",
        "Campeón/Tier List" to "Campeão/Tier List",
        "Tier List / Campeón" to "Tier List / Campeão",
        "Título del reporte o sugerencia" to "Título do relatório ou sugestão",
        "Descripción detallada" to "Descrição detalhada",
        "Ej: El overlay no detecta la pantalla" to "Ex: Overlay não detecta a tela",
        "Ej: Agregar temporizador de dragones con audio" to "Ex: Adicionar cronômetro de dragões com áudio",
        "Ej: Actualizar build recomendada de Veigar" to "Ex: Atualizar build recomendada do Veigar",
        "Describe qué sucedió, cómo reproducirlo o tu idea para mejorar la app..." to "Descreva o que aconteceu, como reproduzir ou sua ideia para melhorar o app...",
        "📱 Diagnóstico:" to "📱 Diagnóstico:",
        "Publicar en GitHub" to "Publicar no GitHub",
        "Copiar" to "Copiar",
        "Copiado" to "Copiado",
        "Abriendo GitHub Issues..." to "Abrindo GitHub Issues...",
        "Reporte copiado al portapapeles ✓" to "Relatório copiado para a área de transferência ✓",
        "Por favor completa el título y la descripción para publicar." to "Por favor, preencha o título e a descrição para publicar.",

        // Botón Activar / Detener Asistente
        "ACTIVAR" to "ATIVAR",
        "DETENER" to "PARAR",
        "ASISTENTE ONLINE" to "ASSISTENTE ONLINE",
        "ASISTENTE OFFLINE" to "ASSISTENTE OFFLINE",
        "Toca para iniciar" to "Toque para iniciar",
        "Toca para finalizar" to "Toque para encerrar",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Pressione ATIVAR para iniciar o Assistente Flutuante",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Assistente Hextech Ativo • Toque na câmera flutuante",

        // Meta Oficial & Rankings
        "Servidor Chino (Tencent / LOLM)" to "Estatísticas do Meta Oficial",
        "Meta Oficial en Vivo" to "Meta Oficial Ao Vivo",
        "Estadísticas del Meta Oficial" to "Estatísticas do Meta Oficial",
        "Estadísticas Oficiales del Meta" to "Estatísticas Oficiais do Meta",
        "Estadísticas Servidor CN (Tencent)" to "Estatísticas do Meta Oficial",
        "Win Rate, Pick, Ban y Variación Diaria (Vs. Ayer)" to "Win Rate, Pick, Ban e Variação Diária (Vs. Ontem)",
        "Sincronizar" to "Sincronizar",
        "Sincronizando..." to "Sincronizando...",
        "⚡ Sincronizando estadísticas oficiales..." to "⚡ Sincronizando estatísticas oficiais...",
        "🟢 En vivo:" to "🟢 Ao vivo:",
        "⚠️ Datos en caché local:" to "⚠️ Dados em cache local:",
        "Instantáneo 24/7" to "Instantâneo 24/7",
        "Rango Activo:" to "Elo Ativo:",
        "Retador / Soberano" to "Desafiante / Soberano",
        "Gran Maestro / Maestro+" to "Grão-Mestre / Mestre+",
        "Soberano" to "Soberano",
        "Maestro+" to "Mestre+",
        "Diamante+" to "Diamante+",
        "Todas las Ligas" to "Todas as Ligas",
        "Todas" to "Todas",
        "Todos los Roles" to "Todas as Funções",
        "Todas las Líneas" to "Todas as Rotas",
        "Buscar campeón por nombre o habilidad..." to "Buscar campeão por nome ou habilidade...",
        "Limpiar" to "Limpar",
        "Vs. Ayer" to "Vs. Ontem",
        "Tasa de Victoria" to "Taxa de Vitória",
        "Tasa de Selección" to "Taxa de Escolha",
        "Tasa de Bloqueo" to "Taxa de Banimento",
        "Elegir como mi Pick" to "Escolher como meu Pick",
        "SELECCIONAR MI PICK PARA" to "SELECIONAR MEU PICK PARA",
        "TU ELECCIÓN EN" to "SUA ESCOLHA NA",
        "Cambiar línea" to "Mudar rota"
    ),
    "en" to mapOf(
        "Línea:" to "Lane:",
        "1er Pick" to "1st Pick",
        "1ª Elección Segura" to "1st Pick (Safe)",
        "Inicio" to "Home",
        "Catálogo" to "Catalog",
        "Top" to "Top",
        "Mid" to "Mid",
        "Jungla" to "Jungle",
        "Dúo" to "Duo",
        "Soporte" to "Support",
        "Flex en " to "Flex in ",
        "Principal: " to "Main: ",
        "Flex: " to "Flex: ",
        "Draft" to "Draft",
        "CDs" to "CDs",
        "Daño" to "Math",
        "Obj" to "Obj",
        "Build" to "Build",
        "Detener Asistente" to "Stop Assistant",
        "Minimizar HUD" to "Minimize HUD",
        "MEJOR OPCIÓN ABSOLUTA" to "BEST ABSOLUTE OPTION",
        "Fijar" to "Lock",
        "y Ver Runas / Build" to "and View Runes / Build",
        "Otras Alternativas en " to "Other Alternatives in ",
        "Selecciona un campeón para ver su página de runas óptima" to "Select a champion to view their optimal rune page",
        "Fijado" to "Locked",
        "Página de Runas" to "Rune Page",
        "Runa Clave Recomendada" to "Recommended Keystone",
        "Selecciona un campeón para ver sus hechizos de invocador recomendados" to "Select a champion to view their recommended summoner spells",
        "Hechizos & Orden de Habilidades" to "Spells & Skill Order",
        "Hechizos de Invocador Recomendados" to "Recommended Summoner Spells",
        "Prioridad de Habilidades" to "Skill Priority (Skill Order)",
        "Maxeo:" to "Max:",
        "Hechizos" to "Spells",
        "Runas" to "Runes",
        "Destello" to "Flash",
        "Prender" to "Ignite",
        "Extenuación" to "Exhaust",
        "Barrera" to "Barrier",
        "Curar" to "Heal",
        "Fantasma" to "Ghost",
        "Estasis" to "Stasis (Zhonya)",
        "Definitiva" to "Ultimate",
        "CD Tracker:" to "CD Tracker:",
        "Rival" to "Enemy",
        "Enfriamiento:" to "Cooldown:",
        "restante" to "remaining",
        "Base:" to "Base:",
        "¡Listo para usar!" to "Ready to use!",
        "Gastado" to "Used",
        "Reiniciar Todos" to "Reset All",
        "Envía fallos o sugerencias. Se guardarán directamente en la base de datos (con retención automática de 7 días):" to "Submit bugs or suggestions. They will be saved directly to the database (with automatic 7-day retention):",
        "Enviar a Base de Datos" to "Send to Database",
        "Enviando a Base de Datos..." to "Sending to Database...",
        "Limpiar Reportes Antiguos (> 7 días)" to "Clean Old Reports (> 7 days)",
        "Módulo de sincronización de la base de datos en la nube. Pulsa el botón para probar la conexión con Supabase o gestionar la retención de reportes." to "Cloud database synchronization module. Press the button to test the connection with Supabase or manage report retention.",

        "Estado del Servidor" to "Server Status (Supabase)",
        "Módulo de sincronización de la base de datos en la nube. Pulsa el botón para probar la conexión con Supabase." to "Cloud database synchronization module. Press the button to test the connection with Supabase.",
        "Conectando con Supabase..." to "Connecting to Supabase...",
        "✅ Conexión exitosa. Cliente inicializado." to "✅ Successful connection. Client initialized.",
        "❌ Error de conexión: " to "❌ Connection error: ",
        "Verificar Conexión Supabase" to "Verify Supabase Connection",


        // Draft UI Extra
        "Equipo Aliado" to "Ally Team",
        "Equipo Rival" to "Enemy Team",
        "Seleccionar Campeón Aliado" to "Select Ally Champion",
        "Seleccionar Campeón Rival" to "Select Enemy Champion",

        // Modal de Bienvenida del Parche
        "¡Bienvenidos a Wild Rift Coach!" to "Welcome to Wild Rift Coach!",
        "Estado del Parche: " to "Patch Status: ",
        "Estado del Parche:" to "Patch Status:",
        "Versión del Parche:" to "Patch Version:",
        "Versión del Parche de Wild Rift:" to "Wild Rift Patch Version:",
        "Parche" to "Patch",
        "parche" to "patch",
        "Parches" to "Patches",
        "parches" to "patches",
        "Parche 7.2c" to "Patch 7.2c",
        "Parche 7.2b" to "Patch 7.2b",
        "Parche 7.2a" to "Patch 7.2a",
        "Parche 7.2" to "Patch 7.2",
        "1. Compatibilidad y Parche Oficial" to "1. Official Patch & Compatibility",
        "Ver Notas de Bienvenida y Novedades del Parche" to "What's New",
        "Novedades" to "What's New",
        "Runas en Español, Parches y Novedades" to "Runes, Patches and Updates",
        "Catálogo Completo de Objetos" to "Complete Item Catalog",
        "Sincronizado con wr-meta.com con descripciones, estadísticas y costes actualizados." to "Synchronized with wr-meta.com with updated descriptions, stats, and gold costs.",
        "Overlay Flotante Táctico" to "Tactical Floating Overlay",
        "Asistente en tiempo real durante tu fase de selección y partida en Wild Rift." to "Real-time assistant during your draft pick and match in Wild Rift.",
        "Seguridad y Rendimiento" to "Security & Performance",
        "Ícono adaptativo optimizado para todas las capas de personalización (Xiaomi/Samsung)." to "Adaptive icon optimized for all custom Android skins (Xiaomi/Samsung).",
        "¡Comenzar / Entendido!" to "Get Started / Understood!",
        "Cerrar" to "Close",

        "¡Bienvenidos!" to "Welcome!",
        "Notas del Nuevo Parche" to "New Patch Notes",
        "• Sincronización automática con: " to "• Automatic synchronization with: ",
        "• Análisis táctico actualizado con las últimas estadísticas del meta.\n" to "• Tactical analysis updated with the latest meta stats.\n",
        "• Ajustes y corrección de íconos rúnicos." to "• Rune icon adjustments and fixes.",
        "Organización: Coach de Élite" to "Organization: Elite Coach (Wild Rift Coach)",
        "Entendido" to "Understood",
        "El rival tiene alta iniciación de CC con Sett y Vi. Se aconseja desengage, escudos antimagia o tenacidad." to "The enemy has high CC engage with Sett and Vi. Recommend disengage, anti-magic shields or tenacity.",
        "Caitlyn rival tiene ventaja de rango en carril de Dragón. Prioriza anulación con Viego o agarre con Nautilus/Blitzcrank." to "Enemy Caitlyn has range advantage in Dragon Lane. Prioritize shutdown with Viego or hooks with Nautilus/Blitzcrank.",
        "Peligro de asesinos de burst" to "Danger of burst assassins",
        "Imprescindible Zhonya/Estasis y CC garantizado (Lulu, Malzahar, Nautilus)." to "Essential Zhonya/Stasis and reliable CC (Lulu, Malzahar, Nautilus).",
        "Composición rival pesada" to "Heavy enemy comp",
        "Requiere daño verdadero y % vida máxima." to "Requires true damage and % max health.",
        "Morgana o Janna" to "Morgana or Janna",
        "Nautilus o Viego" to "Nautilus or Viego",
        "Lulu, Nautilus o Zhonya" to "Lulu, Nautilus or Zhonya",
        "Vayne, Sett, Gwen o Liandry" to "Vayne, Sett, Gwen or Liandry",
        "Conquistador (Precisión)" to "Conqueror (Precision)",
        "Táctico" to "Tactical",
        "Daño Físico" to "Physical Damage",
        "Daño Mágico" to "Magic Damage",
        "Daño Verdadero" to "True Damage",
        "Tanque" to "Tank",
        "Mago" to "Mage",
        "Luchador" to "Fighter",
        "Asesino" to "Assassin",
        "Tirador" to "Marksman",
        "Soporte" to "Support",
        "Top" to "Top",
        "Jungla" to "Jungle",
        "Medio" to "Mid",
        "Dúo" to "Duo",
        "Línea de Barón" to "Baron Lane",
        "Línea de Medio" to "Mid Lane",
        "Línea de Dragón" to "Dragon Lane",
        "💡 Si tu dispositivo muestra 'conflicto con un paquete', desinstala la versión anterior de tu teléfono una sola vez e instala la nueva APK (ocurre por cambio de firma de depurado a producción)." to "💡 If your device shows 'package conflict', uninstall the previous version from your phone once and install the new APK (occurs due to signature change from debug to production)."
,
        "Acerca De" to "About",
        "Asistente Táctico Wild Rift" to "Wild Rift Tactical Assistant",
        "Guía en Tiempo Real para Selección de Campeones" to "Real-Time Guide for Champion Selection",
        "1. Acerca del Asistente" to "1. About the Assistant",
        "Edición Móvil" to "Mobile Edition",
        "• Compatibilidad: Diseñado exclusivamente para Wild Rift (habilidades móviles, runas de Wild Rift, balance y objetos móviles)." to "• Compatibility: Designed exclusively for Wild Rift (mobile skills, Wild Rift runes, balance, and mobile items).",
        "• Parche del juego: " to "• Game patch: ",
        "sincronizado con fuentes de balance." to "synchronized with balance sources.",
        "• Motor Hextech: Botón de activación directa con cálculo de composiciones, counters y sinergias." to "• Hextech Engine: Direct activation button calculating comps, counters, and synergies.",
        "• Sistema Flotante: Ventana superpuesta en pantalla con controles táctiles para la fase de selección." to "• Floating System: Overlay window with touch controls for the drafting phase.",
        "2. Modo de Uso de la Aplicación" to "2. How to Use the App",
        "Paso 1: Configura tus Líneas de Juego" to "Step 1: Configure Your Roles",
        "En la pantalla principal, selecciona tu 'Línea Main', 'Segunda Línea' y 'Rol Autofill' tocando cada tarjeta." to "On the main screen, select your 'Main Role', 'Secondary Role', and 'Autofill Role' by tapping each card.",
        "Paso 2: Activa el Asistente Flotante" to "Step 2: Activate Floating Assistant",
        "Pulsa el botón central 'ACTIVAR'. Se desplegará la burbuja flotante en pantalla para acompañarte en tu partida." to "Press the central 'ACTIVATE' button. The floating bubble will appear on screen to assist you in your match.",
        "Paso 3: Selección de Campeones" to "Step 3: Champion Selection (Champ Select)",
        "Abre Wild Rift y entra a la fase de selección. Toca el botón flotante en cualquier momento para ver recomendaciones, counters y sinergias tácticas en directo." to "Open Wild Rift and enter champ select. Tap the floating button anytime to see live tactical recommendations, counters, and synergies.",
        "Paso 4: Filtros Automáticos" to "Step 4: Automatic Filters",
        "El asistente prioriza campeones según los roles que hayas configurado en el Paso 1, permitiendo una selección más rápida antes de que se acabe el tiempo." to "The assistant prioritizes champions based on the roles configured in Step 1, allowing faster selection before time runs out.",
        "3. Interfaz del Asistente" to "3. Assistant Interface (Overlay HUD)",
        "Pestaña Draft" to "Draft Tab (List Icon)",
        "Recomendaciones de picks seguros, counter picks directos y sinergias basándose en tu rol." to "Safe pick recommendations, direct counter picks, and synergies based on your role.",
        "Pestaña Objetivos" to "Objectives Tab (Map Icon)",
        "Tiempos de reaparición (spawn) de los monstruos neutrales épicos." to "Spawn times of epic neutral monsters.",
        "Pestaña Objetos" to "Items Tab (Sword Icon)",
        "Builds sugeridas para el campeón seleccionado (Core items y situacionales)." to "Suggested builds for the selected champion (Core items and situational).",
        "Pestaña Runas" to "Runes Tab (Magic Icon)",
        "Página de runas meta óptimas para el campeón sugerido." to "Optimal meta rune page for the suggested champion.",
        "Deslizar para Minimizar" to "Swipe to Minimize",
        "Puedes deslizar el panel hacia abajo en cualquier momento para ocultarlo temporalmente sin detener la herramienta." to "You can swipe the panel down anytime to temporarily hide it without stopping the tool.",
        "Versión del Parche de Wild Rift:" to "Wild Rift Patch Version:",
        "Build y Runas de" to "Build and Runes for",
        "Básicos" to "Basic",
        "Nivel Medio" to "Mid Tier",
        "Botas N2" to "Boots T2",
        "Botas N3" to "Boots T3",
        "Encantamientos" to "Actives & Enchants",
        "ÍTEMS BÁSICOS" to "BASIC ITEMS",
        "ÍTEMS DE NIVEL MEDIO" to "MID-TIER ITEMS",
        "DAÑO FÍSICO" to "PHYSICAL DAMAGE",
        "DAÑO MÁGICO" to "MAGIC DAMAGE",
        "DEFENSA" to "DEFENSIVE ITEMS",
        "SOPORTE" to "SUPPORT ITEMS",
        "BOTAS NIVEL 2" to "BOOTS TIER 2",
        "BOTAS NIVEL 3" to "BOOTS TIER 3",
        "ENCANTAMIENTOS Y ACTIVOS" to "ACTIVE & ENCHANTMENT ITEMS",
        "Cuadrícula" to "Grid",
        "Detallado" to "Detailed",
        "Buscar objeto por nombre o estadísticas..." to "Search item by name or stats...",
        "Estadísticas:" to "Stats:",
        "Efecto / Pasiva:" to "Effect / Passive:",
        "Coste:" to "Cost:",
        "Oro" to "Gold",

        "Elige tu idioma" to "Choose your language",
        "Español" to "Spanish",
        "Inglés" to "English",
        "Portugués" to "Portuguese",
        "Continuar" to "Continue",
        "Permiso de Superposición" to "Overlay Permission",
        "Para que el asistente inteligente funcione en segundo plano sobre Wild Rift, Android requiere habilitar 'Aparecer encima' (Superposición)." to "For the smart assistant to run in the background over Wild Rift, Android requires enabling the 'Display over other apps' (Overlay) permission.",
        "El asistente proporciona lecturas de pantalla y sugerencias en tiempo real sin salir del juego." to "The assistant provides screen readings and real-time suggestions without leaving the game.",
        "Conceder Permiso" to "Grant Permission",
        "Cancelar" to "Cancel",
        "Base de Datos Tier List (Parche 16.16.1)" to "Tier List Database (Patch 16.16.1)",
        "Campeones" to "Champions",
        "Sinergias" to "Synergies",
        "Items" to "Items",
        "Runas" to "Runes",
        "Hechizos de Invocador:" to "Summoner Spells:",
        "Árbol de Runas:" to "Rune Tree:",
        "Objetos Básicos:" to "Core Items:",
        "Objetos Situacionales:" to "Situational Items:",
        "Mejores Sinergias:" to "Best Synergies (Composition):",
        "Ventaja Contra:" to "Strong Against:",
        "Débil Contra:" to "Weak Against:",
        "Entendido" to "Understood",
        "Analizando Draft..." to "Analyzing Draft...",
        "Activar Asistente" to "Activate Assistant (Overlay)",
        "Buscando composiciones óptimas y counters..." to "Searching for optimal compositions and counters...",
        "Asistente Wild Rift" to "Wild Rift Assistant",
        "Cerrar" to "Close",
        "Error" to "Error",
        "Información" to "Information",
        "MID" to "MID",
        "TOP" to "TOP",
        "JUNGLE" to "JUNGLE",
        "JUNGLA" to "JUNGLE",
        "ADC" to "DUO",
        "DÚO" to "DUO",
        "Dúo" to "Duo",
        "SUPPORT" to "SUPPORT",
        "SOPORTE" to "SUPPORT",
        "Soporte" to "Support",
        "Jungla" to "Jungle",
        "Top" to "Top",
        "Mid" to "Mid",
        "Ajustes de Posición" to "Position Settings",
        "Se pueden seleccionar hasta 2 posiciones" to "Up to 2 positions can be selected",
        "Daño" to "Damage",
        "Roles" to "Roles",
        "Buscando composiciones..." to "Searching comps...",
        "PermisoSuperposicionTexto" to "1. Tap 'Grant Permission'.\n2. Enable the switch for Wild Rift Coach.\n3. Return to the app and press ACTIVATE.",
        "Línea Main" to "Main Role",
        "Segunda Línea" to "Secondary Role",
        "Rol Autofill" to "Autofill Role",
        "Tier List & Catálogo de Campeones" to "Tier List & Champion Catalog",
        "Tier list, counters, sinergias, runas y objetos" to "Tier list, counters, synergies, runes, and items",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Hextech Assistant Active • Tap the floating camera",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Press ACTIVATE to start the Floating Assistant",
        "★ Mejor Primer Pick Seguro para" to "★ Best Safe First Pick for",
        "★ Mejor Opción según tu Equipo y el Rival" to "★ Best Option for your Team and the Enemy",
        "👑 #1 RECOMENDACIÓN BLIND PICK" to "👑 #1 BLIND PICK RECOMMENDATION",
        "👑 #1 MEJOR ELECCIÓN TÁCTICA" to "👑 #1 BEST TACTICAL CHOICE",
        "Winrate Est.:" to "Est. Winrate:",
        "🔮 Runas recomendadas:" to "🔮 Recommended runes:",
        "Toca para ver build" to "Tap to view build",
        "Otras Opciones Viables para" to "Other Viable Options for",
        "Alerta de Composición Rival" to "Enemy Comp Alert",
        "Añadir" to "Add",
        "Eliminar" to "Remove",
        "ACTIVAR" to "ACTIVATE",
        "DETENER" to "STOP",
        "Volver" to "Back",
        "Reiniciar Draft" to "Reset Draft",
        "Drafting" to "Drafting",
        "Campeones" to "Champions",
        "Tier List" to "Tier List",
        "Objetos" to "Items",
        "Ítems" to "Items",
        "Ítem" to "Item",
        "Runas" to "Runes",
        "Hechizos" to "Spells",
        "Runas & Hechizos" to "Runes & Spells",
        "Objetivos" to "Objectives",
        "Buscar runa..." to "Search rune...",
        "Buscar hechizo..." to "Search spell...",
        "Runas Wild Rift" to "Wild Rift Runes",
        "Hechizos de Invocador" to "Summoner Spells",
        "Runas Clave" to "Keystone Runes",
        "Dominación" to "Domination",
        "Precisión" to "Precision",
        "Valor" to "Resolve",
        "Inspiración" to "Inspiration",
        "Brujería" to "Sorcery",
        "Combate & Daño" to "Combat & Damage",
        "Movilidad & Utilidad" to "Mobility & Utility",
        "Build de" to "Build for",
        "Runas de" to "Runes for",
        "Hechizos de" to "Spells for",
        "Habilidades" to "Abilities",
        "Cambiar" to "Change",

        // Líneas & Roles
        "Línea de Barón" to "Baron Lane",
        "Jungla" to "Jungle",
        "Línea Central" to "Mid Lane",
        "Línea de Dragón" to "Dragon Lane",
        "Soporte" to "Support",
        "Barón" to "Baron",
        "Central" to "Mid",
        "Dragón" to "Dragon",
        "Físico" to "Physical",
        "Mágico" to "Magic",
        "Híbrido / Verdadero" to "Hybrid / True",
        "Daño Físico" to "Physical Damage",
        "Daño Mágico" to "Magic Damage",
        "Poder Mágico" to "Magic Power",
        "Defensa" to "Defense",
        "Objetos Activos" to "Active Items",
        "Botas Nivel 2" to "Tier 2 Boots",
        "Botas Nivel 3" to "Tier 3 Boots",
        "Nivel Medio" to "Mid Tier",
        "Nivel Básico" to "Basic Tier",
        "Utilidad" to "Utility",
        "Botas" to "Boots",
        "Encantamiento" to "Enchantment",
        "Botas & Encantamientos" to "Boots & Enchantments",

        // Hechizos de Invocador
        "Destello" to "Flash",
        "Prender" to "Ignite",
        "Castigo" to "Smite",
        "Barrera" to "Barrier",
        "Extenuación" to "Exhaust",
        "Fantasma" to "Ghost",
        "Curar" to "Heal",
        "Claridad" to "Clarity",
        "Marca / Lanzamiento" to "Mark / Dash",

        // Runas
        "Conquistador" to "Conqueror",
        "Matakrakens" to "Kraken Slayer",
        "Cadencia Letal" to "Lethal Tempo",
        "Electrocutar" to "Electrocute",
        "Primer Golpe" to "First Strike",
        "Irrupción de Fase" to "Phase Rush",
        "Agarre del Perpetuo" to "Grasp of the Undying",
        "Réplica" to "Aftershock",
        "Invocar a Aery" to "Summon Aery",
        "Aumento Glacial" to "Glacial Augment",
        "Cometa Arcano" to "Arcane Comet",
        "Impacto Repentino" to "Sudden Impact",
        "Quemadura" to "Scorch",
        "Colección de Ojos" to "Eyeball Collection",
        "Centinela Zombi" to "Zombie Ward",
        "Triunfo" to "Triumph",
        "Golpe de Gracia" to "Coup de Grace",
        "Último Esfuerzo" to "Last Stand",
        "Leyenda: Celeridad" to "Legend: Alacrity",
        "Revestimiento de Huesos" to "Bone Plating",
        "Segundo Aire" to "Second Wind",
        "Condicionamiento" to "Conditioning",
        "Sobrecrecimiento" to "Overgrowth",
        "Fuente de Vida" to "Font of Life",
        "Dulces Frutos" to "Sweet Tooth",
        "Demolición" to "Demolish",
        "Banda de Flujo de Maná" to "Manaflow Band",
        "Trascendencia" to "Transcendence",
        "Capa del Nimbo" to "Nimbus Cloak",

        "Runa Clave" to "Keystone Rune",
        "Dominación" to "Domination",
        "Precisión" to "Precision",
        "Valor" to "Resolve",
        "Inspiración" to "Inspiration",
        "Brujería" to "Sorcery",
        "Todos" to "All",
        "Hechizos" to "Spells",
        "Runas Clave" to "Keystones",

        "Cambiar Rol / Flex Activo:" to "Change Role / Active Flex:",
        "Toca para alternar" to "Tap to toggle",
        "Análisis Táctico en Wild Rift" to "Tactical Analysis in Wild Rift",
        "Habilidades de" to "Abilities of",
        "Pasiva:" to "Passive:",
        "Habilidad" to "Ability",
        "Definitiva:" to "Ultimate:",
        "¡Nueva Versión Disponible!" to "New Version Available!",
        "Novedades de la actualización:" to "Update Highlights & Notes:",
        "Descargar e Instalar" to "Download & Install",
        "Recordarme más tarde" to "Remind me later",
        "Actualizaciones de la Aplicación" to "App Updates",
        "Buscar Actualizaciones" to "Check for Updates",
        "Comprobando versión..." to "Checking version...",
        "¡Tienes la versión más reciente!" to "You have the latest version!",
        "Ajustes de Posición" to "Lane Display Setting",
        "Se pueden seleccionar hasta 2 posiciones" to "Up to 2 positions can be displayed",
        "SOLO" to "TOP",
        "TOP" to "TOP",
        "Top" to "Top",
        "Barón" to "Baron",
        "BARÓN" to "BARON",
        "JUNGLA" to "JUNGLE",
        "Jungla" to "Jungle",
        "CENTRAL" to "MID",
        "MID" to "MID",
        "Mid" to "Mid",
        "DÚO" to "DUO",
        "Dúo" to "Duo",
        "ADC" to "ADC",
        "SOPORTE" to "SUPPORT",
        "Soporte" to "Support",
        "Todos los Roles" to "All Roles",
        "Todas las Líneas" to "All Lanes",
        "Buscar campeón por nombre o habilidad..." to "Search champion by name or ability...",
        "Buscar objeto por nombre o estadísticas..." to "Search item by name or stats...",
        "Buscar campeón fijado..." to "Search locked champion...",
        "Buscar campeón..." to "Search champion...",
        "Buscar objeto situacional (ej. Heridas, Zhonya)..." to "Search situational item (e.g. Grievous, Zhonya)...",
        "Monstruos Épicos & Tiempos de Aparición" to "Epic Monsters & Spawn Timers",
        "Conocer los tiempos exactos de aparición en Wild Rift asegura la victoria de tu equipo:" to "Knowing exact spawn times in Wild Rift ensures team victory:",
        "Escanear" to "Scan",
        "Coste" to "Cost",
        "Oro" to "Gold",
        "Reaparición" to "Respawn",
        "Reaparición:" to "Respawn:",
        "⚡ Toca para ver info" to "⚡ Tap to view info",
        "Selecciona un campeón para ver su página de runas óptima" to "Select a champion to view optimal rune page",
        "Selecciona un campeón para ver sus hechizos de invocador recomendados" to "Select a champion to view recommended summoner spells",
        "Daño Físico" to "Physical Damage",
        "Poder Mágico" to "Magic Power",
        "Defensa" to "Defense",
        "Botas & Encantamientos" to "Boots & Enchantments",
        "Físico" to "Physical",
        "Mágico" to "Magic",
        "Híbrido / Verdadero" to "Hybrid / True",
        "Principal:" to "Primary:",
        "Flex:" to "Flex:",
        "Objetos Clave (Build Recomendada)" to "Key Items (Recommended Build)",
        "Objetos Básicos:" to "Core Items (Mandatory):",
        "Objetos Situacionales:" to "Situational Items:",
        "¿Por qué comprar este objeto?" to "Why build this item?",
        "Efectivo contra:" to "Effective against:",
        "Efecto clave:" to "Key effect:",
        "Consejo de compra:" to "Purchase tip:",
        "Tasa de Victoria" to "Win Rate",
        "Tasa de Selección" to "Pick Rate",
        "Tasa de Bloqueo" to "Ban Rate",
        "Win Rate" to "Win Rate",
        "Pick Rate" to "Pick Rate",
        "Ban Rate" to "Ban Rate",
        "Hechizos de Invocador" to "Summoner Spells",
        "Runas" to "Runes",
        "Árbol de Runas" to "Rune Tree",
        "Cambiar Línea / Rol Activo:" to "Change Active Role / Lane:",
        "Línea de Barón" to "Baron Lane",
        "Línea Central" to "Mid Lane",
        "Línea de Dragón" to "Dragon Lane",

        // Reports & Suggestions
        "Reportes & Sugerencias" to "Reports & Suggestions",
        "Reporta fallos o envía sugerencias para mejorar el asistente:" to "Report bugs or submit suggestions to improve the assistant:",
        "Reportar Bug" to "Report Bug",
        "Bug / Error" to "Bug / Error",
        "Sugerencia" to "Suggestion",
        "Idea / Mejora" to "Idea / Improvement",
        "Campeón/Tier List" to "Champion/Tier List",
        "Tier List / Campeón" to "Tier List / Champion",
        "Título del reporte o sugerencia" to "Title of report or suggestion",
        "Descripción detallada" to "Detailed description",
        "Ej: El overlay no detecta la pantalla" to "Ex: Overlay does not detect the screen",
        "Ej: Agregar temporizador de dragones con audio" to "Ex: Add dragon timer with audio alert",
        "Ej: Actualizar build recomendada de Veigar" to "Ex: Update Veigar recommended build",
        "Describe qué sucedió, cómo reproducirlo o tu idea para mejorar la app..." to "Describe what happened, how to reproduce it, or your suggestion to improve the app...",
        "📱 Diagnóstico:" to "📱 Diagnostics:",
        "Publicar en GitHub" to "Publish on GitHub",
        "Copiar" to "Copy",
        "Copiado" to "Copied",
        "Abriendo GitHub Issues..." to "Opening GitHub Issues...",
        "Reporte copiado al portapapeles ✓" to "Report copied to clipboard ✓",
        "Por favor completa el título y la descripción para publicar." to "Please complete the title and description to publish.",

        // Activate / Stop Assistant Button
        "ACTIVAR" to "ACTIVATE",
        "DETENER" to "STOP",
        "ASISTENTE ONLINE" to "ASSISTANT ONLINE",
        "ASISTENTE OFFLINE" to "ASSISTANT OFFLINE",
        "Toca para iniciar" to "Tap to start",
        "Toca para finalizar" to "Tap to stop",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Press ACTIVATE to start the Floating Assistant",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Hextech Assistant Active • Tap the floating camera",

        // Meta Oficial & Rankings
        "Servidor Chino (Tencent / LOLM)" to "Official Meta Stats",
        "Meta Oficial en Vivo" to "Live Official Meta",
        "Estadísticas del Meta Oficial" to "Official Meta Statistics",
        "Estadísticas Oficiales del Meta" to "Official Meta Statistics",
        "Estadísticas Servidor CN (Tencent)" to "Official Meta Statistics",
        "Win Rate, Pick, Ban y Variación Diaria (Vs. Ayer)" to "Win Rate, Pick, Ban & Daily Delta (Vs. Yesterday)",
        "Sincronizar" to "Sync",
        "Sincronizando..." to "Syncing...",
        "⚡ Sincronizando estadísticas oficiales..." to "⚡ Syncing official stats...",
        "🟢 En vivo:" to "🟢 Live:",
        "⚠️ Datos en caché local:" to "⚠️ Cached local data:",
        "Instantáneo 24/7" to "Instant 24/7",
        "Rango Activo:" to "Active Rank:",
        "Retador / Soberano" to "Challenger / Sovereign",
        "Gran Maestro / Maestro+" to "Grandmaster / Master+",
        "Soberano" to "Challenger",
        "Maestro+" to "Master+",
        "Diamante+" to "Diamond+",
        "Todas las Ligas" to "All Ranks",
        "Todas" to "All",
        "Todos los Roles" to "All Roles",
        "Todas las Líneas" to "All Lanes",
        "Buscar campeón por nombre o habilidad..." to "Search champion by name or ability...",
        "Limpiar" to "Clear",
        "Vs. Ayer" to "Vs. Yesterday",
        "Tasa de Victoria" to "Win Rate",
        "Tasa de Selección" to "Pick Rate",
        "Tasa de Bloqueo" to "Ban Rate",
        "Elegir como mi Pick" to "Select as my Pick",
        "SELECCIONAR MI PICK PARA" to "SELECT MY PICK FOR",
        "TU ELECCIÓN EN" to "YOUR PICK IN",
        "Cambiar línea" to "Change lane"
    )
)

@Composable
fun tr(key: String): String {
    val lang = LocalLanguage.current
    return trStr(lang, key)
}

fun trStr(lang: String, key: String): String {
    if (lang == "es" || lang == "auto") return key
    val direct = translations[lang]?.get(key)
    if (direct != null) return direct

    // Dynamic patch replacement fallback
    if (lang == "en" || lang == "pt") {
        if (key.startsWith("Parche ")) {
            return "Patch " + key.substring("Parche ".length)
        } else if (key.startsWith("parche ")) {
            return "patch " + key.substring("parche ".length)
        } else if (key == "Parche") {
            return "Patch"
        } else if (key == "parche") {
            return "patch"
        }
    }
    return key
}
